<?php
session_start();

// ⭐⭐⭐ FIX: SET TIMEZONE TO MATCH YOUR LOCAL TIME ⭐⭐⭐
date_default_timezone_set('Asia/Kuala_Lumpur'); // Change to your timezone
// Options: 'Asia/Singapore', 'Asia/Manila', 'Asia/Jakarta', 'UTC', etc.

require_once 'session_check.php'; // Add session check like other pages
require_once 'connection.php';

// Check if user is NOT logged in. If not, redirect to login page.
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

$userRole = $_SESSION['role'] ?? 'Guest';
$username = $_SESSION['username'] ?? 'User';

// Create backup directories
$backup_dir = 'backups/';
$db_backup_dir = $backup_dir . 'database/';
$logs_dir = $backup_dir . 'logs/';

if (!file_exists($db_backup_dir)) {
    mkdir($db_backup_dir, 0777, true);
}
if (!file_exists($logs_dir)) {
    mkdir($logs_dir, 0777, true);
}

// Handle actions
$message = '';
$message_type = '';

// ⭐⭐⭐ UNIVERSAL BACKUP FUNCTION (All 3 DBs) ⭐⭐⭐
function createDatabaseBackup($db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $timestamp = date('Y-m-d_H-i-s');
    $backup_file = $db_backup_dir . "pharmacy_backup_{$db_type}_" . $timestamp . ".sql";
    $log_file = $logs_dir . "backup_log_{$db_type}_" . $timestamp . ".txt";
    
    try {
        // Get all tables from your database
        $tables = ['USER', 'PATIENT', 'MEDICINE', 'PRESCRIPTION', 'PRESCRIPTION_DETAIL'];
        $backup_content = "";
        
        $backup_content .= "-- Pharmacy Database Backup ({$db_type})\n";
        $backup_content .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Generated by: " . $username . "\n";
        $backup_content .= "-- Database Type: " . strtoupper($db_type) . "\n\n";
        
        $total_records = 0;
        
        switch ($db_type) {
            case 'mysql':
                if (!$mysql_conn2) {
                    return ['success' => false, 'message' => "❌ MySQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $query = "SELECT * FROM `$table`";
                    $result = $mysql_conn2->query($query);
                    
                    if ($result && $result->num_rows > 0) {
                        while ($row = $result->fetch_assoc()) {
                            $columns = [];
                            $values = [];
                            
                            foreach ($row as $key => $value) {
                                $columns[] = $key;
                                if ($value === null) {
                                    $values[] = 'NULL';
                                } else {
                                    $values[] = "'" . $mysql_conn2->real_escape_string($value) . "'";
                                }
                            }
                            
                            $backup_content .= "INSERT INTO `$table` (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                            $total_records++;
                        }
                        $result->free();
                    }
                    $backup_content .= "\n";
                }
                break;
                
            case 'sqlserver':
                if (!$pdo) {
                    return ['success' => false, 'message' => "❌ SQL Server connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $stmt = $pdo->prepare("SELECT * FROM [$table]");
                    $stmt->execute();
                    
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                        $columns = [];
                        $values = [];
                        
                        foreach ($row as $key => $value) {
                            $columns[] = $key;
                            if ($value === null) {
                                $values[] = 'NULL';
                            } else {
                                $values[] = "'" . str_replace("'", "''", $value) . "'";
                            }
                        }
                        
                        $backup_content .= "INSERT INTO [$table] (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                        $total_records++;
                    }
                    $backup_content .= "\n";
                }
                break;
                
            case 'postgresql':
                if (!$pg_conn) {
                    return ['success' => false, 'message' => "❌ PostgreSQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $stmt = $pg_conn->prepare("SELECT * FROM \"$table\"");
                    $stmt->execute();
                    
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                        $columns = [];
                        $values = [];
                        
                        foreach ($row as $key => $value) {
                            $columns[] = $key;
                            if ($value === null) {
                                $values[] = 'NULL';
                            } else {
                                $values[] = "'" . str_replace("'", "''", $value) . "'";
                            }
                        }
                        
                        $backup_content .= "INSERT INTO \"$table\" (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                        $total_records++;
                    }
                    $backup_content .= "\n";
                }
                break;
                
            default:
                return ['success' => false, 'message' => "❌ Unknown database type."];
        }
        
        // Save to file
        if (file_put_contents($backup_file, $backup_content)) {
            // Log success
            $log_message = "✅ {$db_type} Backup SUCCESS: " . date('Y-m-d H:i:s') . "\n";
            $log_message .= "User: " . $username . "\n";
            $log_message .= "File: " . basename($backup_file) . "\n";
            $log_message .= "Size: " . filesize($backup_file) . " bytes\n";
            $log_message .= "Tables backed up: " . count($tables) . "\n";
            $log_message .= "Total records: " . $total_records . "\n";
            
            file_put_contents($log_file, $log_message);
            
            return [
                'success' => true,
                'message' => "✅ <strong>" . strtoupper($db_type) . " BACKUP CREATED!</strong><br>
                             File: <strong>" . basename($backup_file) . "</strong><br>
                             Database: " . strtoupper($db_type) . "<br>
                             Size: " . filesize($backup_file) . " bytes<br>
                             Tables: " . count($tables) . "<br>
                             Records: " . $total_records . "<br>
                             Time: " . date('H:i:s'),
                'file' => basename($backup_file),
                'db_type' => $db_type
            ];
        } else {
            return [
                'success' => false,
                'message' => "❌ Failed to write backup file."
            ];
        }
        
    } catch (Exception $e) {
        $error_log = "❌ {$db_type} Backup FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ {$db_type} backup error: " . $e->getMessage()
        ];
    }
}

// ⭐⭐⭐ EXCEL/CSV BACKUP FUNCTION (All 3 DBs) ⭐⭐⭐
function createExcelBackup($db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $timestamp = date('Y-m-d_H-i-s');
    $zip_file = $db_backup_dir . "pharmacy_excel_{$db_type}_" . $timestamp . ".zip";
    $log_file = $logs_dir . "excel_backup_log_{$db_type}_" . $timestamp . ".txt";
    
    try {
        $tables = ['USER', 'PATIENT', 'MEDICINE', 'PRESCRIPTION', 'PRESCRIPTION_DETAIL'];
        $total_records = 0;
        
        // Create ZIP file for all CSV files
        $zip = new ZipArchive();
        if ($zip->open($zip_file, ZipArchive::CREATE) !== TRUE) {
            throw new Exception("Cannot create ZIP file");
        }
        
        switch ($db_type) {
            case 'mysql':
                if (!$mysql_conn2) {
                    return ['success' => false, 'message' => "❌ MySQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $query = "SELECT * FROM `$table`";
                    $result = $mysql_conn2->query($query);
                    
                    if ($result && $result->num_rows > 0) {
                        $csv_content = "";
                        $rowData = $result->fetch_assoc();
                        $headers = array_keys($rowData);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        $result->data_seek(0);
                        while ($row = $result->fetch_assoc()) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                        $result->free();
                    }
                }
                break;
                
            case 'sqlserver':
                if (!$pdo) {
                    return ['success' => false, 'message' => "❌ SQL Server connection not available."];
                }
                
                foreach ($tables as $table) {
                    $stmt = $pdo->prepare("SELECT * FROM [$table]");
                    $stmt->execute();
                    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
                    
                    if ($rows) {
                        $csv_content = "";
                        $headers = array_keys($rows[0]);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        foreach ($rows as $row) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                    }
                }
                break;
                
            case 'postgresql':
                if (!$pg_conn) {
                    return ['success' => false, 'message' => "❌ PostgreSQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $stmt = $pg_conn->prepare("SELECT * FROM \"$table\"");
                    $stmt->execute();
                    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
                    
                    if ($rows) {
                        $csv_content = "";
                        $headers = array_keys($rows[0]);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        foreach ($rows as $row) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                    }
                }
                break;
        }
        
        $zip->close();
        
        // Log success
        $log_message = "✅ {$db_type} Excel Backup SUCCESS: " . date('Y-m-d H:i:s') . "\n";
        $log_message .= "User: " . $username . "\n";
        $log_message .= "File: " . basename($zip_file) . "\n";
        $log_message .= "Size: " . filesize($zip_file) . " bytes\n";
        $log_message .= "Tables backed up: " . count($tables) . "\n";
        $log_message .= "Total records: " . $total_records . "\n";
        
        file_put_contents($log_file, $log_message);
        
        return [
            'success' => true,
            'message' => "✅ <strong>" . strtoupper($db_type) . " EXCEL BACKUP CREATED!</strong><br>
                         File: <strong>" . basename($zip_file) . "</strong><br>
                         Format: ZIP with CSV files<br>
                         Database: " . strtoupper($db_type) . "<br>
                         Size: " . filesize($zip_file) . " bytes<br>
                         Tables: " . count($tables) . "<br>
                         Records: " . $total_records . "<br>
                         Time: " . date('H:i:s'),
            'file' => basename($zip_file),
            'db_type' => $db_type
        ];
        
    } catch (Exception $e) {
        $error_log = "❌ {$db_type} Excel Backup FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ {$db_type} Excel backup error: " . $e->getMessage()
        ];
    }
}

// ⭐⭐⭐ RESTORE DATABASE FUNCTION ⭐⭐⭐
function restoreDatabase($backup_file, $db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $full_path = $db_backup_dir . $backup_file;
    $log_file = $logs_dir . 'restore_log_' . date('Y-m-d_H-i-s') . '.txt';
    
    if (!file_exists($full_path)) {
        return ['success' => false, 'message' => '❌ Backup file not found'];
    }
    
    try {
        $file_ext = strtolower(pathinfo($backup_file, PATHINFO_EXTENSION));
        
        // Log start
        $log_content = "🔧 RESTORE STARTED: " . date('Y-m-d H:i:s') . "\n";
        $log_content .= "User: " . $username . "\n";
        $log_content .= "File: " . $backup_file . "\n";
        $log_content .= "Database: " . strtoupper($db_type) . "\n";
        $log_content .= "File Size: " . filesize($full_path) . " bytes\n\n";
        
        $success = false;
        $records_restored = 0;
        $errors = [];
        
        if ($file_ext === 'sql') {
            // SQL file restore
            $sql_content = file_get_contents($full_path);
            $queries = array_filter(array_map('trim', explode(';', $sql_content)));
            
            if ($db_type === 'mysql' && $mysql_conn2) {
                // Begin transaction
                $mysql_conn2->begin_transaction();
                
                // Temporarily disable foreign key checks
                $mysql_conn2->query("SET FOREIGN_KEY_CHECKS = 0");
                
                // Clear existing data (WARNING: This deletes all data!)
                $tables = ['PRESCRIPTION_DETAIL', 'PRESCRIPTION', 'MEDICINE', 'PATIENT', 'USER'];
                foreach ($tables as $table) {
                    $mysql_conn2->query("DELETE FROM `$table`");
                    $mysql_conn2->query("ALTER TABLE `$table` AUTO_INCREMENT = 1");
                }
                
                // Execute INSERT queries only
                foreach ($queries as $query) {
                    if (!empty($query) && stripos($query, 'INSERT') === 0) {
                        if ($mysql_conn2->query($query)) {
                            $records_restored += $mysql_conn2->affected_rows;
                        } else {
                            $errors[] = "MySQL Error: " . $mysql_conn2->error;
                        }
                    }
                }
                
                $mysql_conn2->query("SET FOREIGN_KEY_CHECKS = 1");
                $mysql_conn2->commit();
                $success = true;
            } else {
                $errors[] = "Only MySQL restoration is currently supported";
            }
        } elseif ($file_ext === 'zip') {
            $errors[] = "CSV/ZIP restoration not yet implemented. Please use SQL files.";
        }
        
        // Log results
        if ($success) {
            $log_content .= "✅ RESTORE COMPLETED SUCCESSFULLY\n";
            $log_content .= "Records restored: " . $records_restored . "\n";
            $log_content .= "Errors: " . count($errors) . "\n";
            
            if (!empty($errors)) {
                $log_content .= "\nERROR DETAILS:\n" . implode("\n", $errors) . "\n";
            }
            
            file_put_contents($log_file, $log_content);
            
            return [
                'success' => true,
                'message' => "✅ <strong>DATABASE RESTORED SUCCESSFULLY!</strong><br>
                             File: <strong>" . $backup_file . "</strong><br>
                             Database: " . strtoupper($db_type) . "<br>
                             Records restored: " . $records_restored . "<br>
                             Time: " . date('H:i:s')
            ];
        } else {
            $log_content .= "❌ RESTORE FAILED\n";
            $log_content .= "Errors: " . implode(", ", $errors) . "\n";
            file_put_contents($log_file, $log_content);
            
            return [
                'success' => false,
                'message' => "❌ Restore failed: " . implode(", ", $errors)
            ];
        }
        
    } catch (Exception $e) {
        $error_log = "❌ RESTORE FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "restore_error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ Restore error: " . $e->getMessage()
        ];
    }
}

// Handle backup creation
if (isset($_POST['create_backup'])) {
    $db_type = $_POST['database_type'] ?? 'mysql';
    $format = $_POST['backup_format'] ?? 'sql';
    
    if ($format === 'excel') {
        $result = createExcelBackup($db_type);
    } else {
        $result = createDatabaseBackup($db_type);
    }
    
    $message = $result['message'];
    $message_type = $result['success'] ? 'success' : 'error';
}

// Handle restore action
if (isset($_POST['restore_backup'])) {
    $backup_file = $_POST['backup_file'] ?? '';
    $database_type = $_POST['database_type'] ?? 'mysql';
    $confirmation = $_POST['confirmation'] ?? '';
    
    if (empty($backup_file)) {
        $message = '❌ Please select a backup file';
        $message_type = 'error';
    } elseif ($confirmation !== 'YES') {
        $message = '❌ You must type YES to confirm restoration';
        $message_type = 'error';
    } else {
        $result = restoreDatabase($backup_file, $database_type);
        $message = $result['message'];
        $message_type = $result['success'] ? 'success' : 'error';
    }
}

// Handle file upload for restore
if (isset($_POST['upload_restore'])) {
    if (isset($_FILES['backup_file']) && $_FILES['backup_file']['error'] === UPLOAD_ERR_OK) {
        $file_tmp = $_FILES['backup_file']['tmp_name'];
        $file_name = basename($_FILES['backup_file']['name']);
        $file_ext = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));
        
        // Validate file type
        if ($file_ext === 'sql' || $file_ext === 'zip') {
            $new_filename = 'uploaded_' . date('Y-m-d_H-i-s') . '_' . $file_name;
            $destination = $db_backup_dir . $new_filename;
            
            if (move_uploaded_file($file_tmp, $destination)) {
                $message = '✅ File uploaded successfully. You can now restore from it.';
                $message_type = 'success';
            } else {
                $message = '❌ Failed to upload file';
                $message_type = 'error';
            }
        } else {
            $message = '❌ Invalid file type. Only .sql or .zip files allowed';
            $message_type = 'error';
        }
    } else {
        $message = '❌ Please select a file to upload';
        $message_type = 'error';
    }
}

// Handle file deletion
if (isset($_GET['delete'])) {
    $file_to_delete = $_GET['delete'];
    $file_path = $db_backup_dir . $file_to_delete;
    
    if (file_exists($file_path)) {
        if (unlink($file_path)) {
            $message = '✅ Backup file deleted successfully';
            $message_type = 'success';
        } else {
            $message = '❌ Failed to delete file';
            $message_type = 'error';
        }
    }
}

// Get existing backup files
$backup_files = [];
if (file_exists($db_backup_dir)) {
    $files = scandir($db_backup_dir);
    foreach ($files as $file) {
        if ($file !== '.' && $file !== '..') {
            $backup_files[] = $file;
        }
    }
}

// Sort by date (newest first)
usort($backup_files, function($a, $b) use ($db_backup_dir) {
    $timeA = file_exists($db_backup_dir . $a) ? filemtime($db_backup_dir . $a) : 0;
    $timeB = file_exists($db_backup_dir . $b) ? filemtime($db_backup_dir . $b) : 0;
    return $timeB - $timeA; // Newest first
});

// Check which databases are available
$mysql_available = ($mysql_conn2 && $mysql_conn2 instanceof mysqli);
$sqlserver_available = (isset($pdo) && $pdo instanceof PDO);
$postgresql_available = (isset($pg_conn) && $pg_conn instanceof PDO);

// Calculate backup stats
$total_size = 0;
foreach ($backup_files as $file) {
    $filepath = $db_backup_dir . $file;
    if (file_exists($filepath)) {
        $total_size += filesize($filepath);
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Backup & Restore | Pharmacy</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400&display=swap" rel="stylesheet">
    <style>
        /* Medical Professional Color Scheme with Dark Blue - SAME AS DASHBOARD */
        :root {
            --dark-blue: #1c4966;
            --blue-medium: #2a5d7a;
            --blue-light: #e3f2fd;
            --blue-accent: #4a90e2;
            --cream-white: #f8fafc;
            --soft-grey: #8a8a8a;
            --dark-grey: #2c3e50;
            --alert-red: #d9534f;
            --warning-orange: #f0ad4e;
            --success-green: #5cb85c;
            
            --sidebar-bg: var(--dark-blue);
            --sidebar-text: white;
            --main-bg: var(--cream-white);
            --card-bg: white;
            --border-color: #e1e8ed;
            --text-primary: var(--dark-grey);
            --text-secondary: var(--soft-grey);
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: "Be Vietnam Pro", sans-serif;
            background: var(--main-bg);
            color: var(--text-primary);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 15px;
            font-weight: 400;
            line-height: 1.5;
        }

        /* DASHBOARD CONTAINER - EXACT SAME SIZE AND STYLE */
        .dashboard-container {
            width: 100%;
            max-width: 1400px;
            height: 92vh;
            background: white;
            border-radius: 12px;
            box-shadow: 0 8px 30px rgba(28, 73, 102, 0.1);
            overflow: hidden;
            display: flex;
        }

        /* SIDEBAR - EXACT SAME AS DASHBOARD */
        .sidebar {
            width: 260px;
            background: linear-gradient(180deg, var(--dark-blue) 0%, #143852 100%);
            color: var(--sidebar-text);
            display: flex;
            flex-direction: column;
            padding: 25px 0;
        }

        .pharmacy-logo {
            text-align: center;
            padding: 0 20px 25px;
            border-bottom: 1px solid rgba(255, 255, 255, 0.15);
        }

        .pharmacy-logo h1 {
            font-size: 1.3em;
            font-weight: 600;
            color: white;
            margin-bottom: 6px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
        }

        .pharmacy-logo p {
            font-size: 0.8em;
            color: rgba(255, 255, 255, 0.85);
            font-weight: 300;
        }

        .user-profile {
            padding: 20px;
            display: flex;
            align-items: center;
            border-bottom: 1px solid rgba(255, 255, 255, 0.15);
        }

        .user-avatar {
            width: 48px;
            height: 48px;
            border-radius: 50%;
            background: linear-gradient(135deg, white, var(--blue-light));
            display: flex;
            align-items: center;
            justify-content: center;
            color: var(--dark-blue);
            font-weight: 600;
            font-size: 1.2em;
            border: 2px solid white;
        }

        .user-info {
            margin-left: 12px;
        }

        .user-name {
            font-weight: 500;
            font-size: 0.95em;
            margin-bottom: 3px;
        }

        .user-role {
            font-size: 0.8em;
            color: rgba(255, 255, 255, 0.9);
            background: rgba(255, 255, 255, 0.15);
            padding: 3px 8px;
            border-radius: 10px;
            display: inline-block;
        }

        /* Navigation Menu - SAME STYLE */
        .nav-menu {
            flex: 1;
            padding: 25px 0;
            overflow-y: auto;
        }

        .nav-section {
            margin-bottom: 25px;
            padding: 0 20px;
        }

        .nav-title {
            font-size: 0.75em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: rgba(255, 255, 255, 0.7);
            margin-bottom: 12px;
            font-weight: 500;
        }

        .nav-links {
            list-style: none;
        }

        .nav-links li {
            margin-bottom: 6px;
        }

        .nav-links a {
            display: flex;
            align-items: center;
            color: rgba(255, 255, 255, 0.9);
            text-decoration: none;
            padding: 10px 12px;
            border-radius: 8px;
            transition: all 0.2s ease;
            border-left: 2px solid transparent;
            font-size: 0.9em;
        }

        .nav-links a:hover {
            background: rgba(255, 255, 255, 0.1);
            color: white;
            border-left-color: var(--blue-accent);
        }

        .nav-links a.active {
            background: rgba(255, 255, 255, 0.15);
            color: white;
            border-left-color: white;
            font-weight: 500;
        }

        .nav-icon {
            width: 20px;
            text-align: center;
            margin-right: 10px;
            font-size: 1em;
        }

        .logout-btn {
            margin: 15px 20px 0;
            padding: 12px;
            background: rgba(255, 255, 255, 0.15);
            color: white;
            border: 1px solid rgba(255, 255, 255, 0.3);
            border-radius: 8px;
            font-size: 0.9em;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.3s ease;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
        }

        .logout-btn:hover {
            background: var(--alert-red);
            border-color: var(--alert-red);
            transform: translateY(-1px);
        }

        /* MAIN CONTENT AREA - EXACT SAME AS DASHBOARD */
        .main-content {
            flex: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
        }

        /* Header - EXACT SAME */
        .main-header {
            padding: 20px 35px;
            background: white;
            border-bottom: 1px solid var(--border-color);
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .header-title h1 {
            font-size: 1.4em;
            color: var(--dark-blue);
            font-weight: 600;
            margin-bottom: 4px;
        }

        .header-title p {
            color: var(--text-secondary);
            font-size: 0.9em;
            font-weight: 300;
        }

        .header-actions {
            display: flex;
            align-items: center;
            gap: 15px;
        }

        .search-box {
            position: relative;
        }

        .search-box input {
            padding: 10px 15px 10px 40px;
            border: 1px solid var(--border-color);
            border-radius: 20px;
            width: 280px;
            font-size: 0.9em;
            background: var(--blue-light);
            transition: all 0.3s ease;
            font-weight: 300;
        }

        .search-box input:focus {
            outline: none;
            border-color: var(--dark-blue);
            box-shadow: 0 0 0 2px rgba(28, 73, 102, 0.1);
            background: white;
        }

        .search-icon {
            position: absolute;
            left: 15px;
            top: 50%;
            transform: translateY(-50%);
            color: var(--dark-blue);
            font-size: 0.9em;
        }

        /* Content Area - EXACT SAME */
        .content-wrapper {
            flex: 1;
            padding: 30px;
            overflow-y: auto;
            background: var(--main-bg);
        }

        /* Welcome Section */
        .welcome-section {
            background: linear-gradient(135deg, var(--dark-blue), var(--blue-medium));
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }

        .welcome-text h2 {
            font-size: 1.5em;
            margin-bottom: 8px;
            font-weight: 600;
        }

        .welcome-text p {
            font-size: 0.95em;
            opacity: 0.9;
            font-weight: 300;
        }

        /* System Navigation */
        .system-nav {
            display: flex;
            gap: 10px;
            padding: 15px;
            background: white;
            border-radius: 10px;
            margin-bottom: 25px;
            border: 1px solid var(--border-color);
            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.04);
            flex-wrap: wrap;
        }

        .system-nav a {
            background: var(--blue-light);
            color: var(--dark-blue);
            font-weight: 500;
            border-radius: 8px;
            padding: 10px 18px;
            text-decoration: none;
            transition: all 0.3s ease;
            border: 1px solid transparent;
            font-size: 0.9em;
        }

        .system-nav a:hover {
            background: var(--blue-accent);
            color: white;
            transform: translateY(-2px);
        }

        .system-nav a.active {
            background: var(--dark-blue);
            color: white;
        }

        /* Alert Messages */
        .alert {
            border-radius: 8px;
            border: none;
            padding: 15px;
            margin-bottom: 20px;
        }

        .alert-success {
            background-color: #d4edda;
            color: #155724;
            border-left: 4px solid var(--success-green);
        }

        .alert-danger {
            background-color: #f8d7da;
            color: #721c24;
            border-left: 4px solid var(--alert-red);
        }

        /* Card Styling */
        .card {
            background: white;
            border-radius: 10px;
            padding: 25px;
            margin-bottom: 25px;
            box-shadow: 0 3px 15px rgba(0, 0, 0, 0.05);
            border: 1px solid var(--border-color);
        }

        /* Database Status Cards */
        .status-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }

        .status-card {
            background: white;
            border-radius: 10px;
            padding: 20px;
            text-align: center;
            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.04);
            border: 1px solid var(--border-color);
            transition: transform 0.2s ease;
        }

        .status-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);
        }

        .status-icon {
            font-size: 2em;
            margin-bottom: 12px;
            color: var(--dark-blue);
        }

        .status-title {
            font-size: 1em;
            font-weight: 600;
            color: var(--text-primary);
            margin-bottom: 6px;
        }

        .status-description {
            color: var(--text-secondary);
            font-size: 0.85em;
            margin-bottom: 10px;
        }

        .status-indicator {
            display: inline-flex;
            align-items: center;
            gap: 5px;
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
        }

        .status-online {
            background: rgba(76, 175, 80, 0.15);
            color: #2e7d32;
            border: 1px solid rgba(76, 175, 80, 0.2);
        }

        .status-offline {
            background: rgba(244, 67, 54, 0.15);
            color: #c62828;
            border: 1px solid rgba(244, 67, 54, 0.2);
        }

        .status-dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            display: inline-block;
        }

        .dot-online {
            background: #4CAF50;
        }

        .dot-offline {
            background: #f44336;
        }

        /* Stats Cards */
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }

        .stat-card {
            background: white;
            border-radius: 10px;
            padding: 20px;
            text-align: center;
            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.04);
            border: 1px solid var(--border-color);
        }

        .stat-value {
            font-size: 2.5em;
            font-weight: 700;
            color: var(--dark-blue);
            margin: 8px 0;
        }

        .stat-label {
            color: var(--text-secondary);
            font-size: 0.85em;
            font-weight: 300;
        }

        /* Tab Navigation */
        .tab-navigation {
            display: flex;
            border-bottom: 2px solid rgba(26, 41, 128, 0.1);
            margin-bottom: 30px;
            overflow-x: auto;
        }

        .tab-button {
            padding: 12px 25px;
            background: none;
            border: none;
            font-weight: 600;
            color: #666;
            cursor: pointer;
            transition: all 0.3s ease;
            border-bottom: 3px solid transparent;
            white-space: nowrap;
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 0.9em;
        }

        .tab-button:hover {
            color: var(--dark-blue);
        }

        .tab-button.active {
            color: var(--dark-blue);
            border-bottom: 3px solid var(--dark-blue);
        }

        .tab-content {
            display: none;
            animation: fadeIn 0.5s ease;
        }

        .tab-content.active {
            display: block;
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }

        /* Backup Format Cards */
        .format-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin: 20px 0;
        }

        .format-card {
            border-radius: 10px;
            padding: 20px;
            transition: all 0.3s ease;
            cursor: pointer;
            border: 2px solid transparent;
            background: white;
            border: 1px solid var(--border-color);
        }

        .format-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
            border-color: var(--dark-blue);
        }

        .format-card.selected {
            border-color: var(--dark-blue);
            background: var(--blue-light);
        }

        .format-icon {
            font-size: 24px;
            margin-bottom: 10px;
            color: var(--dark-blue);
        }

        .format-title {
            font-weight: 700;
            margin-bottom: 10px;
            color: var(--dark-blue);
        }

        .format-features {
            list-style: none;
        }

        .format-features li {
            padding: 5px 0;
            color: var(--text-secondary);
            font-size: 0.85em;
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .format-features li:before {
            content: '✓';
            color: var(--success-green);
            font-weight: bold;
        }

        /* Form Elements */
        .form-group {
            margin-bottom: 20px;
        }

        .form-label {
            display: block;
            margin-bottom: 8px;
            color: var(--dark-blue);
            font-weight: 600;
            font-size: 0.9em;
        }

        .form-control {
            width: 100%;
            padding: 12px 15px;
            border: 1px solid var(--border-color);
            border-radius: 8px;
            font-size: 0.9em;
            transition: all 0.3s ease;
            background: white;
        }

        .form-control:focus {
            border-color: var(--dark-blue);
            box-shadow: 0 0 0 2px rgba(28, 73, 102, 0.1);
            outline: none;
        }

        /* Buttons */
        .btn {
            padding: 12px 24px;
            border-radius: 8px;
            cursor: pointer;
            text-decoration: none;
            color: white;
            font-weight: 600;
            border: none;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            font-size: 0.9em;
            transition: all 0.3s ease;
        }

        .btn-primary {
            background: var(--dark-blue);
        }

        .btn-primary:hover {
            background: var(--blue-medium);
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(28, 73, 102, 0.25);
            color: white;
        }

        .btn-success {
            background: var(--success-green);
        }

        .btn-success:hover {
            background: #4cae4c;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(92, 184, 92, 0.25);
            color: white;
        }

        .btn-danger {
            background: var(--alert-red);
        }

        .btn-danger:hover {
            background: #d43f3a;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(217, 83, 79, 0.25);
            color: white;
        }

        /* Table Styling */
        .table-container {
            background: white;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 3px 15px rgba(0, 0, 0, 0.05);
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9em;
        }

        thead {
            background: var(--dark-blue);
            color: white;
        }

        th {
            padding: 15px;
            text-align: left;
            font-weight: 600;
            font-size: 0.9em;
        }

        td {
            padding: 12px 15px;
            border-bottom: 1px solid var(--border-color);
        }

        tbody tr:hover {
            background-color: var(--blue-light);
            transition: background-color 0.2s ease;
        }

        /* Badges */
        .file-badge {
            display: inline-flex;
            align-items: center;
            gap: 5px;
            padding: 4px 10px;
            border-radius: 15px;
            font-size: 0.75em;
            font-weight: 600;
            color: white;
        }

        .badge-mysql {
            background: linear-gradient(135deg, #4CAF50 0%, #2e7d32 100%);
        }

        .badge-sqlserver {
            background: linear-gradient(135deg, #2196F3 0%, #0d47a1 100%);
        }

        .badge-postgresql {
            background: linear-gradient(135deg, #673AB7 0%, #311b92 100%);
        }

        .badge-format {
            background: linear-gradient(135deg, #FF9800 0%, #ef6c00 100%);
        }

        /* Action Buttons */
        .action-buttons {
            display: flex;
            gap: 8px;
        }

        .btn-action {
            padding: 6px 12px;
            border-radius: 6px;
            font-size: 0.8em;
            font-weight: 600;
            border: none;
            cursor: pointer;
            transition: all 0.2s ease;
            display: inline-flex;
            align-items: center;
            gap: 5px;
            text-decoration: none;
        }

        .btn-download {
            background: var(--dark-blue);
            color: white;
        }

        .btn-delete {
            background: var(--alert-red);
            color: white;
        }

        .btn-action:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        /* Restore Warning */
        .restore-warning {
            background: linear-gradient(135deg, #fff3cd 0%, #ffeaa7 100%);
            border-left: 4px solid #ffc107;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 25px;
        }

        .restore-warning h4 {
            color: #856404;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .confirmation-input {
            border: 2px solid #dc3545 !important;
            font-weight: bold;
            text-align: center;
            letter-spacing: 2px;
        }

        /* Upload Area */
        .upload-area {
            border: 2px dashed var(--dark-blue);
            border-radius: 10px;
            padding: 40px;
            text-align: center;
            margin: 20px 0;
            background: var(--blue-light);
            transition: all 0.3s ease;
            cursor: pointer;
        }

        .upload-area:hover {
            background: rgba(28, 73, 102, 0.1);
            border-color: var(--blue-accent);
        }

        /* Responsive Design */
        @media (max-width: 1200px) {
            .dashboard-container {
                height: auto;
                flex-direction: column;
            }
            
            .sidebar {
                width: 100%;
                height: auto;
            }
            
            .nav-menu {
                display: flex;
                flex-wrap: wrap;
                gap: 10px;
                padding: 15px;
            }
            
            .nav-section {
                flex: 1;
                min-width: 200px;
                margin-bottom: 15px;
            }
            
            .main-content {
                width: 100%;
            }
            
            .system-nav {
                overflow-x: auto;
            }
            
            .status-grid,
            .stats-grid {
                grid-template-columns: repeat(2, 1fr);
                gap: 15px;
            }
        }

        @media (max-width: 768px) {
            .content-wrapper {
                padding: 20px;
            }
            
            .main-header {
                padding: 15px 20px;
                flex-direction: column;
                align-items: flex-start;
                gap: 15px;
            }
            
            .search-box input {
                width: 100%;
            }
            
            .header-actions {
                width: 100%;
            }
            
            .welcome-section {
                padding: 20px;
            }
            
            .system-nav a {
                padding: 8px 12px;
                font-size: 0.85em;
            }
            
            .status-grid,
            .stats-grid,
            .format-grid {
                grid-template-columns: 1fr;
            }
            
            .card {
                padding: 20px;
            }
            
            table {
                font-size: 0.85em;
            }
            
            th, td {
                padding: 10px;
            }
        }

        @media (max-width: 480px) {
            .sidebar {
                padding: 15px 0;
            }
            
            .pharmacy-logo h1 {
                font-size: 1.1em;
            }
            
            .user-profile {
                padding: 15px;
            }
            
            .content-wrapper {
                padding: 15px;
            }
            
            .tab-button {
                padding: 10px 15px;
                font-size: 0.8em;
            }
        }
    </style>
</head>
<body>
    <!-- DASHBOARD CONTAINER - EXACT SAME STRUCTURE -->
    <div class="dashboard-container">
        <!-- SIDEBAR - EXACT SAME AS DASHBOARD -->
        <aside class="sidebar">
            <div class="pharmacy-logo">
                <h1><i class="fas fa-pills"></i> PHARMACY SYSTEM</h1>
                <p>Professional Healthcare Management</p>
            </div>

            <div class="user-profile">
                <div class="user-avatar">
                    <?php echo strtoupper(substr($username, 0, 2)); ?>
                </div>
                <div class="user-info">
                    <div class="user-name"><?php echo htmlspecialchars($username); ?></div>
                    <div class="user-role"><?php echo htmlspecialchars($userRole); ?></div>
                </div>
            </div>

            <nav class="nav-menu">
                <div class="nav-section">
                    <div class="nav-title">Medical Operations</div>
                    <ul class="nav-links">
                        <li><a href="dashboard.php"><i class="fas fa-home nav-icon"></i>Dashboard</a></li>
                        <li><a href="medDirectory.php"><i class="fas fa-pills nav-icon"></i>Medicine Inventory</a></li>
                        <li><a href="prescriptionDashboard.php"><i class="fas fa-prescription nav-icon"></i>Prescriptions</a></li>
                        <li><a href="Sales_Billing.php"><i class="fas fa-cash-register nav-icon"></i>Sales & Billing</a></li>
                    </ul>
                </div>

                <div class="nav-section">
                    <div class="nav-title">Administration</div>
                    <ul class="nav-links">
                        <li><a href="user_management.php"><i class="fas fa-users nav-icon"></i>User Management</a></li>
                        <li><a href="reports.php"><i class="fas fa-chart-bar nav-icon"></i>Reports & Analytics</a></li>
                        <li><a href="backup.php" class="active"><i class="fas fa-database nav-icon"></i>Backup & Restore</a></li>
                    </ul>
                </div>
            </nav>

            <button class="logout-btn" onclick="window.location.href='logout.php'">
                <i class="fas fa-sign-out-alt"></i> Log Out
            </button>
        </aside>

        <!-- MAIN CONTENT -->
        <main class="main-content">
            <header class="main-header">
                <div class="header-title">
                    <h1>Backup & Restore</h1>
                    <p>Manage database backups and restorations - <?php echo date('l, F j, Y H:i:s'); ?></p>
                </div>
                <div class="header-actions">
                    <div class="search-box">
                        <i class="fas fa-search search-icon"></i>
                        <input type="text" placeholder="Search backup files...">
                    </div>
                </div>
            </header>

            <div class="content-wrapper">
                <!-- Welcome Section -->
                <section class="welcome-section">
                    <div class="welcome-text">
                        <h2><i class="fas fa-database"></i> Backup & Restore Console</h2>
                        <p>Backup, restore, and manage data from all connected databases</p>
                    </div>
                </section>

                <!-- System Navigation -->
                <div class="system-nav">
                    <a href="dashboard.php"><i class="fas fa-home"></i> Dashboard</a>
                    <a href="user_management.php"><i class="fas fa-users"></i> User Management</a>
                    <a href="medDirectory.php"><i class="fas fa-pills"></i> Medicine Inventory</a>
                    <a href="Sales_Billing.php"><i class="fas fa-cash-register"></i> Sales & Billing</a>
                    <a href="reports.php"><i class="fas fa-chart-bar"></i> Reports & Analytics</a>
                    <a href="backup.php" class="active"><i class="fas fa-database"></i> Backup & Restore</a>
                </div>

                <!-- Messages -->
                <?php if ($message): ?>
                    <div class="alert <?php echo $message_type === 'success' ? 'alert-success' : 'alert-danger'; ?>">
                        <?php echo $message; ?>
                    </div>
                <?php endif; ?>
                
                <!-- Database Status -->
                <div class="card">
                    <h3 style="color: var(--dark-blue); margin-bottom: 20px; display: flex; align-items: center; gap: 10px;">
                        <i class="fas fa-server"></i> Database Status
                    </h3>
                    <div class="status-grid">
                        <div class="status-card">
                            <div class="status-icon">
                                <i class="fas fa-database"></i>
                            </div>
                            <div class="status-name">MySQL</div>
                            <div class="status-indicator <?php echo $mysql_available ? 'status-online' : 'status-offline'; ?>">
                                <span class="status-dot <?php echo $mysql_available ? 'dot-online' : 'dot-offline'; ?>"></span>
                                <?php echo $mysql_available ? 'Connected' : 'Not Connected'; ?>
                            </div>
                            <div class="status-description">Your Local Database (Full Backup & Restore)</div>
                        </div>
                        
                        <div class="status-card">
                            <div class="status-icon">
                                <i class="fas fa-server"></i>
                            </div>
                            <div class="status-name">SQL Server</div>
                            <div class="status-indicator <?php echo $sqlserver_available ? 'status-online' : 'status-offline'; ?>">
                                <span class="status-dot <?php echo $sqlserver_available ? 'dot-online' : 'dot-offline'; ?>"></span>
                                <?php echo $sqlserver_available ? 'Connected' : 'Not Connected'; ?>
                            </div>
                            <div class="status-description">Team Member Database (Backup Only)</div>
                        </div>
                        
                        <div class="status-card">
                            <div class="status-icon">
                                <i class="fas fa-database"></i>
                            </div>
                            <div class="status-name">PostgreSQL</div>
                            <div class="status-indicator <?php echo $postgresql_available ? 'status-online' : 'status-offline'; ?>">
                                <span class="status-dot <?php echo $postgresql_available ? 'dot-online' : 'dot-offline'; ?>"></span>
                                <?php echo $postgresql_available ? 'Connected' : 'Not Connected'; ?>
                            </div>
                            <div class="status-description">Team Member Database (Backup Only)</div>
                        </div>
                    </div>
                </div>
                
                <!-- Backup Statistics -->
                <div class="card">
                    <h3 style="color: var(--dark-blue); margin-bottom: 20px; display: flex; align-items: center; gap: 10px;">
                        <i class="fas fa-chart-bar"></i> Backup Statistics
                    </h3>
                    <div class="stats-grid">
                        <div class="stat-card">
                            <div class="stat-value"><?php echo count($backup_files); ?></div>
                            <div class="stat-label">Total Backups</div>
                        </div>
                        
                        <div class="stat-card">
                            <div class="stat-value">
                                <?php
                                echo formatBytes($total_size);
                                ?>
                            </div>
                            <div class="stat-label">Storage Used</div>
                        </div>
                        
                        <div class="stat-card">
                            <div class="stat-value">
                                <?php echo count(array_filter($backup_files, function($f) { return strpos($f, '_mysql_') !== false; })); ?>
                            </div>
                            <div class="stat-label">MySQL Backups</div>
                        </div>
                        
                        <div class="stat-card">
                            <div class="stat-value">
                                <?php echo count(array_filter($backup_files, function($f) { 
                                    return strpos($f, '_sqlserver_') !== false || strpos($f, '_postgresql_') !== false; 
                                })); ?>
                            </div>
                            <div class="stat-label">Team Backups</div>
                        </div>
                    </div>
                </div>

                <!-- Backup Control Panel -->
                <div class="card">
                    <!-- Tab Navigation -->
                    <div class="tab-navigation">
                        <button class="tab-button active" onclick="showTab('create')">
                            <i class="fas fa-plus-circle"></i> Create Backup
                        </button>
                        <button class="tab-button" onclick="showTab('restore')">
                            <i class="fas fa-history"></i> Restore
                        </button>
                        <button class="tab-button" onclick="showTab('upload')">
                            <i class="fas fa-upload"></i> Upload
                        </button>
                        <button class="tab-button" onclick="showTab('files')">
                            <i class="fas fa-folder-open"></i> Backup Files
                        </button>
                    </div>
                    
                    <!-- CREATE BACKUP TAB -->
                    <div id="tab-create" class="tab-content active">
                        <h4 style="color: var(--dark-blue); margin-bottom: 20px; text-align: center;">
                            <i class="fas fa-cloud-upload-alt"></i> Create New Database Backup
                        </h4>
                        
                        <form method="POST" action="">
                            <div class="form-group">
                                <label class="form-label">Select Database</label>
                                <select name="database_type" class="form-control" onchange="updateDbStatus(this.value)">
                                    <option value="mysql" <?php echo $mysql_available ? '' : 'disabled'; ?>>
                                        MySQL <?php echo $mysql_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                    </option>
                                    <option value="sqlserver" <?php echo $sqlserver_available ? '' : 'disabled'; ?>>
                                        SQL Server <?php echo $sqlserver_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                    </option>
                                    <option value="postgresql" <?php echo $postgresql_available ? '' : 'disabled'; ?>>
                                        PostgreSQL <?php echo $postgresql_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                    </option>
                                </select>
                                <small id="db-status-text" style="color: var(--text-secondary); margin-top: 5px; display: block;">
                                    <?php echo $mysql_available ? 'MySQL is available for backup' : 'Select an available database'; ?>
                                </small>
                            </div>
                            
                            <div class="form-group">
                                <label class="form-label">Backup Format</label>
                                <div class="format-grid">
                                    <div class="format-card" onclick="selectFormat('sql')" id="format-sql">
                                        <div class="format-icon">
                                            <i class="fas fa-database"></i>
                                        </div>
                                        <div class="format-title">SQL Format</div>
                                        <ul class="format-features">
                                            <li>Creates .sql file</li>
                                            <li>Contains INSERT statements</li>
                                            <li>Best for database restoration</li>
                                            <li>Compatible with all databases</li>
                                        </ul>
                                    </div>
                                    
                                    <div class="format-card" onclick="selectFormat('excel')" id="format-excel">
                                        <div class="format-icon">
                                            <i class="fas fa-file-excel"></i>
                                        </div>
                                        <div class="format-title">Excel/CSV Format</div>
                                        <ul class="format-features">
                                            <li>Creates .zip with CSV files</li>
                                            <li>Open in Excel/Google Sheets</li>
                                            <li>Best for reporting/analysis</li>
                                            <li>Easy data sharing</li>
                                        </ul>
                                    </div>
                                </div>
                                <input type="hidden" name="backup_format" id="backup_format" value="sql">
                            </div>
                            
                            <div class="form-group">
                                <label class="form-label">Backup Name (Optional)</label>
                                <input type="text" name="backup_name" class="form-control" 
                                       value="Pharmacy_Backup_<?php echo date('Y-m-d'); ?>" 
                                       placeholder="Enter a descriptive name for your backup">
                            </div>
                            
                            <button type="submit" name="create_backup" class="btn btn-primary" style="width: 100%;">
                                <i class="fas fa-rocket"></i> Create Backup Now
                            </button>
                            
                            <p style="margin-top: 15px; text-align: center; color: var(--text-secondary); font-size: 0.85em;">
                                <i class="fas fa-info-circle"></i> This will backup all tables: USER, PATIENT, MEDICINE, PRESCRIPTION, PRESCRIPTION_DETAIL
                            </p>
                        </form>
                    </div>
                    
                    <!-- RESTORE TAB -->
                    <div id="tab-restore" class="tab-content">
                        <h4 style="color: var(--dark-blue); margin-bottom: 20px; text-align: center;">
                            <i class="fas fa-history"></i> Restore Database from Backup
                        </h4>
                        
                        <div class="restore-warning">
                            <h4><i class="fas fa-exclamation-triangle"></i> IMPORTANT WARNING</h4>
                            <p>Restoring a backup will OVERWRITE all existing data in the selected database. This action cannot be undone.</p>
                            <ul style="margin: 10px 0; padding-left: 20px;">
                                <li>Make sure you have a current backup before proceeding</li>
                                <li>Only restore to the same database type (MySQL to MySQL, etc.)</li>
                                <li>Large restores may take several minutes</li>
                                <li>All users will be logged out during restoration</li>
                            </ul>
                        </div>
                        
                        <form method="POST" action="" onsubmit="return confirmRestore()">
                            <div class="form-group">
                                <label class="form-label">Select Backup File</label>
                                <select name="backup_file" class="form-control" required>
                                    <option value="">-- Select a backup file --</option>
                                    <?php foreach ($backup_files as $file): 
                                        $filepath = $db_backup_dir . $file;
                                        if (file_exists($filepath)):
                                    ?>
                                        <option value="<?php echo htmlspecialchars($file); ?>">
                                            <?php echo htmlspecialchars($file); ?> 
                                            (<?php echo date('M d, Y H:i', filemtime($filepath)); ?>)
                                        </option>
                                    <?php endif; endforeach; ?>
                                </select>
                            </div>
                            
                            <div class="form-group">
                                <label class="form-label">Target Database</label>
                                <select name="database_type" class="form-control" required>
                                    <option value="mysql" <?php echo $mysql_available ? '' : 'disabled'; ?>>
                                        MySQL <?php echo $mysql_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                    </option>
                                    <option value="sqlserver" disabled>SQL Server (Restore not available)</option>
                                    <option value="postgresql" disabled>PostgreSQL (Restore not available)</option>
                                </select>
                                <small style="color: var(--text-secondary); margin-top: 5px; display: block;">
                                    Note: Restoration is only available for MySQL. Team databases are read-only.
                                </small>
                            </div>
                            
                            <div class="form-group">
                                <label class="form-label">
                                    <i class="fas fa-exclamation-circle"></i> Type "YES" to confirm
                                </label>
                                <input type="text" name="confirmation" class="form-control confirmation-input" 
                                       placeholder="TYPE: YES" required pattern="YES">
                                <small style="color: var(--text-secondary); margin-top: 5px; display: block;">
                                    This is required to prevent accidental data loss
                                </small>
                            </div>
                            
                            <button type="submit" name="restore_backup" class="btn btn-danger" style="width: 100%;">
                                <i class="fas fa-bomb"></i> RESTORE DATABASE NOW
                            </button>
                        </form>
                    </div>
                    
                    <!-- UPLOAD TAB -->
                    <div id="tab-upload" class="tab-content">
                        <h4 style="color: var(--dark-blue); margin-bottom: 20px; text-align: center;">
                            <i class="fas fa-cloud-upload-alt"></i> Upload Backup File
                        </h4>
                        
                        <form method="POST" action="" enctype="multipart/form-data">
                            <div class="upload-area" onclick="document.getElementById('fileInput').click()">
                                <i class="fas fa-file-upload" style="font-size: 48px; color: var(--dark-blue); margin-bottom: 15px;"></i>
                                <h4>Click to select backup file</h4>
                                <p style="color: var(--text-secondary);">Supported formats: .sql, .zip</p>
                                <p style="color: var(--soft-grey); font-size: 0.85em;">Max file size: 50MB</p>
                                <input type="file" id="fileInput" name="backup_file" 
                                       accept=".sql,.zip" style="display: none;" 
                                       onchange="document.getElementById('fileName').textContent = this.files[0].name">
                                <div id="fileName" style="margin-top: 15px; font-weight: 600; color: var(--dark-blue);"></div>
                            </div>
                            
                            <div class="form-group">
                                <label class="form-label">File Description (Optional)</label>
                                <input type="text" name="description" class="form-control" 
                                       placeholder="e.g., Emergency backup from Dec 2024">
                            </div>
                            
                            <button type="submit" name="upload_restore" class="btn btn-primary" style="width: 100%;">
                                <i class="fas fa-upload"></i> Upload Backup File
                            </button>
                        </form>
                    </div>
                    
                    <!-- BACKUP FILES TAB -->
                    <div id="tab-files" class="tab-content">
                        <h4 style="color: var(--dark-blue); margin-bottom: 20px; text-align: center;">
                            <i class="fas fa-archive"></i> Backup Files Archive
                        </h4>
                        
                        <?php if (count($backup_files) > 0): ?>
                            <div class="table-container">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Filename</th>
                                            <th>Database</th>
                                            <th>Format</th>
                                            <th>Size</th>
                                            <th>Date</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($backup_files as $file): 
                                            $filepath = $db_backup_dir . $file;
                                            $filesize = file_exists($filepath) ? formatBytes(filesize($filepath)) : 'N/A';
                                            $filedate = file_exists($filepath) ? date('M d, Y H:i', filemtime($filepath)) : 'N/A';
                                            $fileext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
                                            
                                            // Determine database type from filename
                                            if (strpos($file, '_mysql_') !== false) {
                                                $db_type = 'MySQL';
                                                $db_class = 'badge-mysql';
                                            } elseif (strpos($file, '_sqlserver_') !== false) {
                                                $db_type = 'SQL Server';
                                                $db_class = 'badge-sqlserver';
                                            } elseif (strpos($file, '_postgresql_') !== false) {
                                                $db_type = 'PostgreSQL';
                                                $db_class = 'badge-postgresql';
                                            } else {
                                                $db_type = 'Unknown';
                                                $db_class = 'badge-format';
                                            }
                                            
                                            $format = ($fileext === 'zip') ? 'Excel/CSV' : 'SQL';
                                        ?>
                                            <tr>
                                                <td style="font-weight: 600; font-size: 0.9em;"><?php echo htmlspecialchars($file); ?></td>
                                                <td><span class="file-badge <?php echo $db_class; ?>"><?php echo $db_type; ?></span></td>
                                                <td><span class="file-badge badge-format"><?php echo $format; ?></span></td>
                                                <td><?php echo $filesize; ?></td>
                                                <td><?php echo $filedate; ?></td>
                                                <td>
                                                    <div class="action-buttons">
                                                        <a href="backups/database/<?php echo urlencode($file); ?>" 
                                                           download class="btn-action btn-download">
                                                            <i class="fas fa-download"></i> Download
                                                        </a>
                                                        <a href="?delete=<?php echo urlencode($file); ?>" 
                                                           class="btn-action btn-delete"
                                                           onclick="return confirm('Are you sure you want to delete <?php echo htmlspecialchars($file); ?>?')">
                                                            <i class="fas fa-trash"></i> Delete
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php else: ?>
                            <div style="text-align: center; padding: 40px; background: var(--blue-light); border-radius: 8px;">
                                <i class="fas fa-folder-open" style="font-size: 48px; color: var(--border-color); margin-bottom: 15px;"></i>
                                <p style="color: var(--text-secondary); font-size: 1.1em;">No backup files found</p>
                                <p style="color: var(--soft-grey); margin-top: 10px;">Create your first backup using the "Create Backup" tab</p>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <script>
        // Tab functionality
        function showTab(tabName) {
            // Hide all tabs
            document.querySelectorAll('.tab-content').forEach(tab => {
                tab.classList.remove('active');
            });
            
            // Remove active class from all tab buttons
            document.querySelectorAll('.tab-button').forEach(button => {
                button.classList.remove('active');
            });
            
            // Show selected tab
            document.getElementById('tab-' + tabName).classList.add('active');
            
            // Add active class to clicked tab button
            event.target.classList.add('active');
        }
        
        // Format selection
        function selectFormat(format) {
            // Remove selected class from all format cards
            document.querySelectorAll('.format-card').forEach(card => {
                card.classList.remove('selected');
            });
            
            // Add selected class to clicked card
            document.getElementById('format-' + format).classList.add('selected');
            
            // Set hidden input value
            document.getElementById('backup_format').value = format;
        }
        
        // Database status update
        function updateDbStatus(selectedDb) {
            const statusText = document.getElementById('db-status-text');
            const dbStatus = {
                'mysql': '<?php echo $mysql_available ? "✅ MySQL is available for backup" : "❌ MySQL is not connected"; ?>',
                'sqlserver': '<?php echo $sqlserver_available ? "✅ SQL Server is available for backup" : "❌ SQL Server is not connected"; ?>',
                'postgresql': '<?php echo $postgresql_available ? "✅ PostgreSQL is available for backup" : "❌ PostgreSQL is not connected"; ?>'
            };
            statusText.textContent = dbStatus[selectedDb] || 'Select a database';
        }
        
        // Restore confirmation
        function confirmRestore() {
            const confirmation = document.querySelector('input[name="confirmation"]').value;
            if (confirmation !== 'YES') {
                alert('You must type YES to confirm restoration');
                return false;
            }
            
            return confirm('⚠️ FINAL WARNING: This will OVERWRITE all data in your database.\n\nThis action cannot be undone!\n\nAre you absolutely sure?');
        }
        
        // Initialize format selection
        document.addEventListener('DOMContentLoaded', function() {
            selectFormat('sql');
            
            const select = document.querySelector('select[name="database_type"]');
            if (select) {
                updateDbStatus(select.value);
            }
            
            // Search functionality
            document.querySelector('.search-box input').addEventListener('keypress', function(e) {
                if (e.key === 'Enter') {
                    const searchTerm = this.value.trim();
                    if (searchTerm) {
                        // Implement search functionality here
                        alert('Search function would filter backup files. Implementation pending.');
                    }
                }
            });
            
            // Clear search on escape
            document.querySelector('.search-box input').addEventListener('keyup', function(e) {
                if (e.key === 'Escape') {
                    this.value = '';
                }
            });
        });
        
        // Sidebar navigation active state
        document.querySelectorAll('.nav-links a').forEach(link => {
            link.addEventListener('click', function(e) {
                // Store active page in sessionStorage before navigation
                sessionStorage.setItem('activePage', this.getAttribute('href'));
            });
        });
        
        // Restore active page on page load
        document.addEventListener('DOMContentLoaded', function() {
            const currentPage = window.location.pathname.split('/').pop();
            const activePage = sessionStorage.getItem('activePage') || 'backup.php';
            
            document.querySelectorAll('.nav-links a').forEach(link => {
                const linkPage = link.getAttribute('href');
                link.classList.remove('active');
                
                if (linkPage === currentPage || linkPage === activePage) {
                    link.classList.add('active');
                }
            });
        });
    </script>
</body>
</html>
<?php
// Helper function to format file sizes
function formatBytes($bytes, $precision = 2) {
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    
    return round($bytes, $precision) . ' ' . $units[$pow];
}