<?php
session_start();
require_once 'connection.php';

// Check if user is NOT logged in. If not, redirect to login page.
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

$userRole = $_SESSION['role'] ?? 'Guest';
$username = $_SESSION['username'] ?? 'User';

// Create backup directories
$backup_dir = 'backups/';
$db_backup_dir = $backup_dir . 'database/';
$logs_dir = $backup_dir . 'logs/';

if (!file_exists($db_backup_dir)) {
    mkdir($db_backup_dir, 0777, true);
}
if (!file_exists($logs_dir)) {
    mkdir($logs_dir, 0777, true);
}

// Handle actions
$message = '';
$message_type = '';

// ⭐⭐⭐ UNIVERSAL BACKUP FUNCTION (All 3 DBs) ⭐⭐⭐
function createDatabaseBackup($db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $timestamp = date('Y-m-d_H-i-s');
    $backup_file = $db_backup_dir . "pharmacy_backup_{$db_type}_" . $timestamp . ".sql";
    $log_file = $logs_dir . "backup_log_{$db_type}_" . $timestamp . ".txt";
    
    try {
        // Get all tables from your database
        $tables = ['USER', 'PATIENT', 'MEDICINE', 'PRESCRIPTION', 'PRESCRIPTION_DETAIL'];
        $backup_content = "";
        
        $backup_content .= "-- Pharmacy Database Backup ({$db_type})\n";
        $backup_content .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Generated by: " . $username . "\n";
        $backup_content .= "-- Database Type: " . strtoupper($db_type) . "\n\n";
        
        $total_records = 0;
        
        switch ($db_type) {
            case 'mysql':
                if (!$mysql_conn2) {
                    return ['success' => false, 'message' => "❌ MySQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $query = "SELECT * FROM `$table`";
                    $result = $mysql_conn2->query($query);
                    
                    if ($result && $result->num_rows > 0) {
                        while ($row = $result->fetch_assoc()) {
                            $columns = [];
                            $values = [];
                            
                            foreach ($row as $key => $value) {
                                $columns[] = $key;
                                if ($value === null) {
                                    $values[] = 'NULL';
                                } else {
                                    $values[] = "'" . $mysql_conn2->real_escape_string($value) . "'";
                                }
                            }
                            
                            $backup_content .= "INSERT INTO `$table` (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                            $total_records++;
                        }
                        $result->free();
                    }
                    $backup_content .= "\n";
                }
                break;
                
            case 'sqlserver':
                if (!$pdo) {
                    return ['success' => false, 'message' => "❌ SQL Server connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $stmt = $pdo->prepare("SELECT * FROM [$table]");
                    $stmt->execute();
                    
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                        $columns = [];
                        $values = [];
                        
                        foreach ($row as $key => $value) {
                            $columns[] = $key;
                            if ($value === null) {
                                $values[] = 'NULL';
                            } else {
                                $values[] = "'" . str_replace("'", "''", $value) . "'";
                            }
                        }
                        
                        $backup_content .= "INSERT INTO [$table] (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                        $total_records++;
                    }
                    $backup_content .= "\n";
                }
                break;
                
            case 'postgresql':
                if (!$pg_conn) {
                    return ['success' => false, 'message' => "❌ PostgreSQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $stmt = $pg_conn->prepare("SELECT * FROM \"$table\"");
                    $stmt->execute();
                    
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                        $columns = [];
                        $values = [];
                        
                        foreach ($row as $key => $value) {
                            $columns[] = $key;
                            if ($value === null) {
                                $values[] = 'NULL';
                            } else {
                                $values[] = "'" . str_replace("'", "''", $value) . "'";
                            }
                        }
                        
                        $backup_content .= "INSERT INTO \"$table\" (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                        $total_records++;
                    }
                    $backup_content .= "\n";
                }
                break;
                
            default:
                return ['success' => false, 'message' => "❌ Unknown database type."];
        }
        
        // Save to file
        if (file_put_contents($backup_file, $backup_content)) {
            // Log success
            $log_message = "✅ {$db_type} Backup SUCCESS: " . date('Y-m-d H:i:s') . "\n";
            $log_message .= "User: " . $username . "\n";
            $log_message .= "File: " . basename($backup_file) . "\n";
            $log_message .= "Size: " . filesize($backup_file) . " bytes\n";
            $log_message .= "Tables backed up: " . count($tables) . "\n";
            $log_message .= "Total records: " . $total_records . "\n";
            
            file_put_contents($log_file, $log_message);
            
            return [
                'success' => true,
                'message' => "✅ <strong>" . strtoupper($db_type) . " BACKUP CREATED!</strong><br>
                             File: <strong>" . basename($backup_file) . "</strong><br>
                             Database: " . strtoupper($db_type) . "<br>
                             Size: " . filesize($backup_file) . " bytes<br>
                             Tables: " . count($tables) . "<br>
                             Records: " . $total_records,
                'file' => basename($backup_file),
                'db_type' => $db_type
            ];
        } else {
            return [
                'success' => false,
                'message' => "❌ Failed to write backup file."
            ];
        }
        
    } catch (Exception $e) {
        $error_log = "❌ {$db_type} Backup FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ {$db_type} backup error: " . $e->getMessage()
        ];
    }
}

// ⭐⭐⭐ EXCEL/CSV BACKUP FUNCTION (All 3 DBs) ⭐⭐⭐
function createExcelBackup($db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $timestamp = date('Y-m-d_H-i-s');
    $zip_file = $db_backup_dir . "pharmacy_excel_{$db_type}_" . $timestamp . ".zip";
    $log_file = $logs_dir . "excel_backup_log_{$db_type}_" . $timestamp . ".txt";
    
    try {
        $tables = ['USER', 'PATIENT', 'MEDICINE', 'PRESCRIPTION', 'PRESCRIPTION_DETAIL'];
        $total_records = 0;
        
        // Create ZIP file for all CSV files
        $zip = new ZipArchive();
        if ($zip->open($zip_file, ZipArchive::CREATE) !== TRUE) {
            throw new Exception("Cannot create ZIP file");
        }
        
        switch ($db_type) {
            case 'mysql':
                if (!$mysql_conn2) {
                    return ['success' => false, 'message' => "❌ MySQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $query = "SELECT * FROM `$table`";
                    $result = $mysql_conn2->query($query);
                    
                    if ($result && $result->num_rows > 0) {
                        $csv_content = "";
                        $rowData = $result->fetch_assoc();
                        $headers = array_keys($rowData);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        $result->data_seek(0);
                        while ($row = $result->fetch_assoc()) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                        $result->free();
                    }
                }
                break;
                
            case 'sqlserver':
                if (!$pdo) {
                    return ['success' => false, 'message' => "❌ SQL Server connection not available."];
                }
                
                foreach ($tables as $table) {
                    $stmt = $pdo->prepare("SELECT * FROM [$table]");
                    $stmt->execute();
                    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
                    
                    if ($rows) {
                        $csv_content = "";
                        $headers = array_keys($rows[0]);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        foreach ($rows as $row) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                    }
                }
                break;
                
            case 'postgresql':
                if (!$pg_conn) {
                    return ['success' => false, 'message' => "❌ PostgreSQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $stmt = $pg_conn->prepare("SELECT * FROM \"$table\"");
                    $stmt->execute();
                    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
                    
                    if ($rows) {
                        $csv_content = "";
                        $headers = array_keys($rows[0]);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        foreach ($rows as $row) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                    }
                }
                break;
        }
        
        $zip->close();
        
        // Log success
        $log_message = "✅ {$db_type} Excel Backup SUCCESS: " . date('Y-m-d H:i:s') . "\n";
        $log_message .= "User: " . $username . "\n";
        $log_message .= "File: " . basename($zip_file) . "\n";
        $log_message .= "Size: " . filesize($zip_file) . " bytes\n";
        $log_message .= "Tables backed up: " . count($tables) . "\n";
        $log_message .= "Total records: " . $total_records . "\n";
        
        file_put_contents($log_file, $log_message);
        
        return [
            'success' => true,
            'message' => "✅ <strong>" . strtoupper($db_type) . " EXCEL BACKUP CREATED!</strong><br>
                         File: <strong>" . basename($zip_file) . "</strong><br>
                         Format: ZIP with CSV files<br>
                         Database: " . strtoupper($db_type) . "<br>
                         Size: " . filesize($zip_file) . " bytes<br>
                         Tables: " . count($tables) . "<br>
                         Records: " . $total_records,
            'file' => basename($zip_file),
            'db_type' => $db_type
        ];
        
    } catch (Exception $e) {
        $error_log = "❌ {$db_type} Excel Backup FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ {$db_type} Excel backup error: " . $e->getMessage()
        ];
    }
}

// ⭐⭐⭐ RECOVER/RESTORE FUNCTION (For MySQL only - since it's your local DB) ⭐⭐⭐
function restoreDatabaseBackup($backup_file) {
    global $mysql_conn2, $logs_dir, $username;
    
    try {
        $log_file = $logs_dir . "restore_log_" . date('Y-m-d_H-i-s') . ".txt";
        
        // Check file type
        $file_ext = strtolower(pathinfo($backup_file, PATHINFO_EXTENSION));
        
        if ($file_ext === 'zip') {
            // Handle ZIP/CSV restore
            return restoreFromCSV($backup_file);
        } else {
            // Handle SQL restore
            return restoreFromSQL($backup_file);
        }
        
    } catch (Exception $e) {
        $error_log = "❌ Restore FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ Restore error: " . $e->getMessage()
        ];
    }
}

function restoreFromSQL($backup_file) {
    global $mysql_conn2, $logs_dir, $username;
    
    $log_file = $logs_dir . "restore_log_" . date('Y-m-d_H-i-s') . ".txt";
    
    // Read backup file
    $backup_content = file_get_contents($backup_file);
    if (!$backup_content) {
        return [
            'success' => false,
            'message' => "❌ Cannot read backup file."
        ];
    }
    
    // Log restore start
    $log_message = "🔄 SQL Restore STARTED: " . date('Y-m-d H:i:s') . "\n";
    $log_message .= "User: " . $username . "\n";
    $log_message .= "File: " . basename($backup_file) . "\n";
    file_put_contents($log_file, $log_message, FILE_APPEND);
    
    // Split SQL statements
    $sql_statements = explode(";", $backup_content);
    $restored_tables = [];
    $restored_records = 0;
    
    // Begin transaction
    $mysql_conn2->begin_transaction();
    
    // Clear existing data first
    $tables = ['PRESCRIPTION_DETAIL', 'PRESCRIPTION', 'MEDICINE', 'PATIENT', 'USER'];
    foreach ($tables as $table) {
        $delete_query = "DELETE FROM `$table`";
        if ($mysql_conn2->query($delete_query)) {
            $log_message = "Cleared table: $table\n";
            file_put_contents($log_file, $log_message, FILE_APPEND);
        }
    }
    
    // Execute each SQL statement
    foreach ($sql_statements as $sql) {
        $sql = trim($sql);
        if (!empty($sql) && stripos($sql, 'INSERT INTO') === 0) {
            if ($mysql_conn2->query($sql)) {
                $restored_records++;
                
                // Extract table name
                if (preg_match('/INSERT INTO `?(\w+)`?/i', $sql, $matches)) {
                    $table_name = $matches[1];
                    if (!in_array($table_name, $restored_tables)) {
                        $restored_tables[] = $table_name;
                    }
                }
            } else {
                throw new Exception("Failed to execute SQL: " . $mysql_conn2->error);
            }
        }
    }
    
    // Commit transaction
    $mysql_conn2->commit();
    
    // Log success
    $log_message = "✅ SQL Restore COMPLETED: " . date('Y-m-d H:i:s') . "\n";
    $log_message .= "Tables restored: " . count($restored_tables) . "\n";
    $log_message .= "Records restored: " . $restored_records . "\n";
    file_put_contents($log_file, $log_message, FILE_APPEND);
    
    return [
        'success' => true,
        'message' => "✅ <strong>DATABASE RESTORED FROM SQL!</strong><br>
                     File: <strong>" . basename($backup_file) . "</strong><br>
                     Format: SQL<br>
                     Tables: " . count($restored_tables) . "<br>
                     Records: " . $restored_records,
        'tables' => $restored_tables,
        'records' => $restored_records
    ];
}

function restoreFromCSV($backup_file) {
    global $mysql_conn2, $logs_dir, $username;
    
    $log_file = $logs_dir . "restore_log_" . date('Y-m-d_H-i-s') . ".txt";
    
    // Log restore start
    $log_message = "🔄 CSV Restore STARTED: " . date('Y-m-d H:i:s') . "\n";
    $log_message .= "User: " . $username . "\n";
    $log_message .= "File: " . basename($backup_file) . "\n";
    file_put_contents($log_file, $log_message, FILE_APPEND);
    
    $restored_tables = [];
    $restored_records = 0;
    
    // Begin transaction
    $mysql_conn2->begin_transaction();
    
    // Clear existing data first
    $tables = ['PRESCRIPTION_DETAIL', 'PRESCRIPTION', 'MEDICINE', 'PATIENT', 'USER'];
    foreach ($tables as $table) {
        $delete_query = "DELETE FROM `$table`";
        if ($mysql_conn2->query($delete_query)) {
            $log_message = "Cleared table: $table\n";
            file_put_contents($log_file, $log_message, FILE_APPEND);
        }
    }
    
    // Extract ZIP and process CSV files
    $zip = new ZipArchive();
    if ($zip->open($backup_file) === TRUE) {
        for ($i = 0; $i < $zip->numFiles; $i++) {
            $filename = $zip->getNameIndex($i);
            
            // Check if it's a CSV file
            if (pathinfo($filename, PATHINFO_EXTENSION) === 'csv') {
                $table_name = pathinfo($filename, PATHINFO_FILENAME);
                $csv_content = $zip->getFromIndex($i);
                
                // Parse CSV
                $lines = explode("\n", $csv_content);
                $headers = str_getcsv($lines[0]);
                
                // Process each row
                for ($j = 1; $j < count($lines); $j++) {
                    if (empty(trim($lines[$j]))) continue;
                    
                    $row = str_getcsv($lines[$j]);
                    $values = [];
                    
                    foreach ($row as $value) {
                        if ($value === '') {
                            $values[] = 'NULL';
                        } else {
                            $values[] = "'" . $mysql_conn2->real_escape_string($value) . "'";
                        }
                    }
                    
                    $sql = "INSERT INTO `$table_name` (" . implode(', ', $headers) . ") VALUES (" . implode(', ', $values) . ")";
                    if ($mysql_conn2->query($sql)) {
                        $restored_records++;
                        if (!in_array($table_name, $restored_tables)) {
                            $restored_tables[] = $table_name;
                        }
                    }
                }
            }
        }
        $zip->close();
    }
    
    // Commit transaction
    $mysql_conn2->commit();
    
    // Log success
    $log_message = "✅ CSV Restore COMPLETED: " . date('Y-m-d H:i:s') . "\n";
    $log_message .= "Tables restored: " . count($restored_tables) . "\n";
    $log_message .= "Records restored: " . $restored_records . "\n";
    file_put_contents($log_file, $log_message, FILE_APPEND);
    
    return [
        'success' => true,
        'message' => "✅ <strong>DATABASE RESTORED FROM CSV!</strong><br>
                     File: <strong>" . basename($backup_file) . "</strong><br>
                     Format: CSV/Excel<br>
                     Tables: " . count($restored_tables) . "<br>
                     Records: " . $restored_records,
        'tables' => $restored_tables,
        'records' => $restored_records
    ];
}

// Handle backup creation
if (isset($_POST['create_backup'])) {
    $db_type = $_POST['database_type'] ?? 'mysql';
    $format = $_POST['backup_format'] ?? 'sql';
    
    if ($format === 'excel') {
        $result = createExcelBackup($db_type);
    } else {
        $result = createDatabaseBackup($db_type);
    }
    
    $message = $result['message'];
    $message_type = $result['success'] ? 'success' : 'error';
}

// Handle file restore (only for MySQL backups)
if (isset($_POST['restore_backup'])) {
    // Handle uploaded file
    if (isset($_FILES['backup_file']) && $_FILES['backup_file']['error'] === UPLOAD_ERR_OK) {
        $uploaded_file = $_FILES['backup_file']['tmp_name'];
        $result = restoreDatabaseBackup($uploaded_file);
        $message = $result['message'];
        $message_type = $result['success'] ? 'success' : 'error';
    } else {
        $message = "❌ Please select a valid backup file to upload.";
        $message_type = 'error';
    }
}

// Handle file restore from existing backups (only MySQL files)
if (isset($_GET['restore'])) {
    $filename = $_GET['restore'];
    $filepath = $db_backup_dir . basename($filename);
    
    // Check if it's a MySQL backup (only MySQL can be restored locally)
    if (strpos($filename, '_mysql_') === false) {
        $message = "❌ Only MySQL backups can be restored on this system.<br>SQL Server and PostgreSQL backups are for other team members.";
        $message_type = 'error';
    } elseif (file_exists($filepath)) {
        $result = restoreDatabaseBackup($filepath);
        $message = $result['message'];
        $message_type = $result['success'] ? 'success' : 'error';
    } else {
        $message = "❌ Backup file not found: " . htmlspecialchars($filename);
        $message_type = 'error';
    }
}

// Handle file deletion
if (isset($_GET['delete'])) {
    $filename = $_GET['delete'];
    $filepath = $db_backup_dir . basename($filename);
    
    if (file_exists($filepath) && unlink($filepath)) {
        $message = "✅ Backup file deleted: " . htmlspecialchars($filename);
        $message_type = 'success';
    } else {
        $message = "❌ Failed to delete backup file.";
        $message_type = 'error';
    }
}

// Get existing backup files
$backup_files = [];
if (file_exists($db_backup_dir)) {
    $files = scandir($db_backup_dir);
    foreach ($files as $file) {
        if ($file !== '.' && $file !== '..') {
            $backup_files[] = $file;
        }
    }
}

// Sort by date (newest first)
usort($backup_files, function($a, $b) use ($db_backup_dir) {
    $timeA = file_exists($db_backup_dir . $a) ? filemtime($db_backup_dir . $a) : 0;
    $timeB = file_exists($db_backup_dir . $b) ? filemtime($db_backup_dir . $b) : 0;
    return $timeB - $timeA; // Newest first
});

// Check which databases are available
$mysql_available = ($mysql_conn2 && $mysql_conn2 instanceof mysqli);
$sqlserver_available = (isset($pdo) && $pdo instanceof PDO);
$postgresql_available = (isset($pg_conn) && $pg_conn instanceof PDO);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Backup & Restore - Pharmacy System</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #0066ff 0%, #0099ff 100%); min-height: 100vh; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; background: white; border-radius: 15px; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2); overflow: hidden; }
        
        .header { 
            background: linear-gradient(135deg, #0066ff 0%, #0099ff 100%); 
            color: white; 
            padding: 25px 30px; 
            text-align: center; 
        }
        .header h1 { font-size: 2em; margin: 0; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); }
        
        .controls-top {
            padding: 20px 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: white;
            border-bottom: 1px solid #eee;
        }
        
        .btn {
            padding: 10px 20px;
            border-radius: 8px;
            border: none;
            cursor: pointer;
            font-size: 0.95em;
            font-weight: 500;
            transition: all 0.3s ease;
            text-decoration: none;
            display: inline-flex;
            align-items: center;
            gap: 8px;
        }
        .btn-primary { background: #0066ff; color: white; }
        .btn-secondary { background: #6c757d; color: white; }
        .btn-success { background: #28a745; color: white; }
        .btn-danger { background: #dc3545; color: white; }
        .btn-warning { background: #ffc107; color: #212529; }
        .btn-info { background: #17a2b8; color: white; }
        
        .btn:hover { transform: translateY(-2px); box-shadow: 0 5px 15px rgba(0,0,0,0.1); }
        
        .content { padding: 30px; }
        
        .card {
            background: white;
            border-radius: 10px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            padding: 25px;
            border-top: 4px solid #0066ff;
        }
        
        .card h2 {
            color: #0066ff;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        
        .form-group { margin-bottom: 20px; }
        .form-group label { display: block; margin-bottom: 8px; font-weight: 600; color: #333; }
        .form-control {
            width: 100%;
            padding: 10px 15px;
            border: 1px solid #ddd;
            border-radius: 6px;
            font-size: 1em;
        }
        
        .db-status {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin-bottom: 25px;
        }
        
        .db-card {
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }
        .db-card.mysql { background: #e8f5e9; border: 2px solid #4caf50; }
        .db-card.sqlserver { background: #e3f2fd; border: 2px solid #2196f3; }
        .db-card.postgresql { background: #f3e5f5; border: 2px solid #9c27b0; }
        
        .status-indicator {
            display: inline-block;
            width: 12px;
            height: 12px;
            border-radius: 50%;
            margin-right: 8px;
        }
        .status-online { background: #4caf50; }
        .status-offline { background: #f44336; }
        
        .tabs {
            display: flex;
            border-bottom: 1px solid #ddd;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }
        .tab {
            padding: 12px 24px;
            cursor: pointer;
            border-bottom: 3px solid transparent;
            white-space: nowrap;
        }
        .tab.active {
            border-bottom: 3px solid #0066ff;
            color: #0066ff;
            font-weight: 600;
        }
        .tab-content { display: none; }
        .tab-content.active { display: block; }
        
        .message {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            animation: fadeIn 0.5s;
        }
        .message.success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .message.error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .message.info { background: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; }
        .message.warning { background: #fff3cd; color: #856404; border: 1px solid #ffeaa7; }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(-10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        .format-info {
            display: flex;
            gap: 20px;
            margin-top: 15px;
        }
        .format-card {
            flex: 1;
            padding: 15px;
            border-radius: 8px;
        }
        .format-card.sql { border: 2px solid #0066ff; background: #e3f2fd; }
        .format-card.excel { border: 2px solid #28a745; background: #e8f5e9; }
        
        .file-type-badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            font-weight: bold;
            margin-left: 10px;
        }
        .badge-mysql { background: #4caf50; color: white; }
        .badge-sqlserver { background: #2196f3; color: white; }
        .badge-postgresql { background: #9c27b0; color: white; }
        .badge-excel { background: #28a745; color: white; }
        .badge-sql { background: #6c757d; color: white; }
        
        .backup-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .backup-table th, .backup-table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        .backup-table th {
            background: #f8f9fa;
            color: #333;
            font-weight: 600;
        }
        .backup-table tr:hover { background: #f8f9fa; }
        
        .file-actions { display: flex; gap: 8px; }
        
        .restore-note {
            background: #fff3cd;
            border: 1px solid #ffc107;
            color: #856404;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
            font-size: 0.9em;
        }
        
        .restore-btn {
            position: relative;
        }
        .restore-btn:after {
            content: "🔁";
            font-size: 0.8em;
            margin-left: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="controls-top">
            <div>
                <a href="dashboard.php" class="btn btn-secondary">← Back to Dashboard</a>
                <span style="margin-left: 20px; font-weight: 600;">
                    Logged in as: <strong><?php echo htmlspecialchars($username); ?></strong> (Role: <strong><?php echo htmlspecialchars($userRole); ?></strong>)
                </span>
            </div>
            <a href="logout.php" class="btn btn-secondary">Log Out</a>
        </div>
        
        <header class="header">
            <h1>💾 Multi-Database Backup & Restore System</h1>
            <p style="opacity: 0.9; margin-top: 10px;">Backup from all 3 databases + Restore for MySQL</p>
        </header>
        
        <div class="content">
            <?php if ($message): ?>
                <div class="message <?php echo $message_type; ?>">
                    <?php echo $message; ?>
                </div>
            <?php endif; ?>
            
            <!-- Database Status -->
            <div class="db-status">
                <div class="db-card mysql">
                    <h3>MySQL <span class="status-indicator <?php echo $mysql_available ? 'status-online' : 'status-offline'; ?>"></span></h3>
                    <p><?php echo $mysql_available ? '✅ Connected' : '❌ Not connected'; ?></p>
                    <small>Your Local Database (Backup + Restore)</small>
                </div>
                <div class="db-card sqlserver">
                    <h3>SQL Server <span class="status-indicator <?php echo $sqlserver_available ? 'status-online' : 'status-offline'; ?>"></span></h3>
                    <p><?php echo $sqlserver_available ? '✅ Connected' : '❌ Not connected'; ?></p>
                    <small>Team Member (Backup Only)</small>
                </div>
                <div class="db-card postgresql">
                    <h3>PostgreSQL <span class="status-indicator <?php echo $postgresql_available ? 'status-online' : 'status-offline'; ?>"></span></h3>
                    <p><?php echo $postgresql_available ? '✅ Connected' : '❌ Not connected'; ?></p>
                    <small>Team Member (Backup Only)</small>
                </div>
            </div>
            
            <!-- Tabs for different sections -->
            <div class="tabs" id="tabs">
                <div class="tab active" onclick="showTab('backup')">📥 Create Backup</div>
                <div class="tab" onclick="showTab('restore')">📤 Restore Backup</div>
                <div class="tab" onclick="showTab('files')">📁 Backup Files</div>
                <div class="tab" onclick="showTab('logs')">📋 Logs</div>
            </div>
            
            <!-- Tab 1: Create Backup -->
            <div id="tab-backup" class="tab-content active">
                <div class="card">
                    <h2>📥 Create New Backup</h2>
                    
                    <div class="format-info">
                        <div class="format-card sql">
                            <strong>📊 SQL Format</strong>
                            <p>• Creates .sql file</p>
                            <p>• Contains INSERT statements</p>
                            <p>• Best for database restoration</p>
                        </div>
                        <div class="format-card excel">
                            <strong>📈 Excel/CSV Format</strong>
                            <p>• Creates .zip with CSV files</p>
                            <p>• Open in Excel/Google Sheets</p>
                            <p>• Best for reporting/analysis</p>
                        </div>
                    </div>
                    
                    <form method="POST" action="">
                        <div class="form-group">
                            <label>Select Database</label>
                            <select name="database_type" class="form-control" onchange="updateDbStatus(this.value)">
                                <option value="mysql" <?php echo $mysql_available ? '' : 'disabled'; ?>>MySQL <?php echo $mysql_available ? '✅' : '❌'; ?></option>
                                <option value="sqlserver" <?php echo $sqlserver_available ? '' : 'disabled'; ?>>SQL Server <?php echo $sqlserver_available ? '✅' : '❌'; ?></option>
                                <option value="postgresql" <?php echo $postgresql_available ? '' : 'disabled'; ?>>PostgreSQL <?php echo $postgresql_available ? '✅' : '❌'; ?></option>
                            </select>
                            <small id="db-status-text" style="color: #666;">
                                <?php echo $mysql_available ? 'MySQL is available for backup' : 'No databases available'; ?>
                            </small>
                        </div>
                        
                        <div class="form-group">
                            <label>Backup Format</label>
                            <select name="backup_format" class="form-control">
                                <option value="sql">SQL Format (.sql) - For database restoration</option>
                                <option value="excel">Excel/CSV Format (.zip) - For reports in Excel</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label>Backup Name (Optional)</label>
                            <input type="text" name="backup_name" class="form-control" 
                                   value="Pharmacy_Backup_<?php echo date('Y-m-d'); ?>" 
                                   placeholder="Enter backup name">
                        </div>
                        
                        <button type="submit" name="create_backup" class="btn btn-primary" style="width: 100%; padding: 12px;">
                            🚀 Create Backup
                        </button>
                        
                        <p style="margin-top: 15px; font-size: 0.9em; color: #666; text-align: center;">
                            Creates a backup of the selected database. Only available databases can be backed up.
                        </p>
                    </form>
                </div>
            </div>
            
            <!-- Tab 2: Restore Backup -->
            <div id="tab-restore" class="tab-content">
                <div class="card">
                    <h2>📤 Restore Database (MySQL Only)</h2>
                    
                    <div class="restore-note">
                        <strong>⚠️ IMPORTANT:</strong> 
                        <p>• Only <strong>MySQL backups</strong> can be restored on this system</p>
                        <p>• SQL Server and PostgreSQL backups are for team members</p>
                        <p>• This will DELETE all current MySQL data before restoring</p>
                    </div>
                    
                    <!-- Option 1: Upload backup file -->
                    <h3>Option 1: Upload Backup File</h3>
                    <form method="POST" action="" enctype="multipart/form-data" onsubmit="return confirmRestore()">
                        <div class="form-group">
                            <label>Select Backup File (MySQL backups only)</label>
                            <input type="file" name="backup_file" class="form-control" accept=".sql,.zip,.txt" required>
                            <p style="font-size: 0.85em; color: #666; margin-top: 5px;">
                                Supported formats: .sql, .zip (with CSV files)
                            </p>
                        </div>
                        
                        <button type="submit" name="restore_backup" class="btn btn-warning restore-btn" style="width: 100%; padding: 12px;">
                            🔄 Upload & Restore MySQL Database
                        </button>
                    </form>
                    
                    <!-- Option 2: Select from existing MySQL backups -->
                    <div style="margin-top: 30px;">
                        <h3>Option 2: Restore from Existing MySQL Backup</h3>
                        <?php 
                        // Filter only MySQL backup files
                        $mysql_backup_files = array_filter($backup_files, function($file) {
                            return strpos($file, '_mysql_') !== false;
                        });
                        ?>
                        
                        <?php if (count($mysql_backup_files) > 0): ?>
                            <table class="backup-table" style="margin-top: 15px;">
                                <thead>
                                    <tr>
                                        <th>Filename</th>
                                        <th>Size</th>
                                        <th>Date</th>
                                        <th>Format</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($mysql_backup_files as $file): 
                                        $filepath = $db_backup_dir . $file;
                                        $filesize = file_exists($filepath) ? formatBytes(filesize($filepath)) : 'N/A';
                                        $filedate = file_exists($filepath) ? date('Y-m-d H:i', filemtime($filepath)) : 'N/A';
                                        $fileext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
                                        $format_badge = $fileext === 'zip' ? 
                                            '<span class="file-type-badge badge-excel">Excel</span>' : 
                                            '<span class="file-type-badge badge-sql">SQL</span>';
                                    ?>
                                        <tr>
                                            <td><strong><?php echo htmlspecialchars($file); ?></strong></td>
                                            <td><?php echo $filesize; ?></td>
                                            <td><?php echo $filedate; ?></td>
                                            <td><?php echo $format_badge; ?></td>
                                            <td>
                                                <a href="?restore=<?php echo urlencode($file); ?>" 
                                                   class="btn btn-warning restore-btn" style="padding: 8px 15px;"
                                                   onclick="return confirm('⚠️ CRITICAL: This will DELETE all current MySQL data and restore from <?php echo htmlspecialchars($file); ?>!\n\nAre you ABSOLUTELY sure?')">
                                                    🔄 Restore
                                                </a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>
                            <p style="color: #666; text-align: center; padding: 20px; background: #f8f9fa; border-radius: 8px;">
                                No MySQL backup files found. Create a MySQL backup first.
                            </p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            
            <!-- Tab 3: Backup Files -->
            <div id="tab-files" class="tab-content">
                <div class="card">
                    <h2>📁 Existing Backup Files</h2>
                    
                    <?php if (count($backup_files) > 0): ?>
                        <table class="backup-table">
                            <thead>
                                <tr>
                                    <th>Filename</th>
                                    <th>Size</th>
                                    <th>Date</th>
                                    <th>Database</th>
                                    <th>Format</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($backup_files as $file): 
                                    $filepath = $db_backup_dir . $file;
                                    $filesize = file_exists($filepath) ? formatBytes(filesize($filepath)) : 'N/A';
                                    $filedate = file_exists($filepath) ? date('Y-m-d H:i', filemtime($filepath)) : 'N/A';
                                    $fileext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
                                    
                                    // Determine database type from filename
                                    $db_badge = '';
                                    if (strpos($file, '_mysql_') !== false) {
                                        $db_badge = '<span class="file-type-badge badge-mysql">MySQL</span>';
                                    } elseif (strpos($file, '_sqlserver_') !== false) {
                                        $db_badge = '<span class="file-type-badge badge-sqlserver">SQL Server</span>';
                                    } elseif (strpos($file, '_postgresql_') !== false) {
                                        $db_badge = '<span class="file-type-badge badge-postgresql">PostgreSQL</span>';
                                    }
                                    
                                    $format_badge = $fileext === 'zip' ? 
                                        '<span class="file-type-badge badge-excel">Excel</span>' : 
                                        '<span class="file-type-badge badge-sql">SQL</span>';
                                    
                                    // Check if restore is available (only for MySQL)
                                    $can_restore = (strpos($file, '_mysql_') !== false);
                                ?>
                                    <tr>
                                        <td><strong><?php echo htmlspecialchars($file); ?></strong></td>
                                        <td><?php echo $filesize; ?></td>
                                        <td><?php echo $filedate; ?></td>
                                        <td><?php echo $db_badge; ?></td>
                                        <td><?php echo $format_badge; ?></td>
                                        <td>
                                            <div class="file-actions">
                                                <a href="backups/database/<?php echo urlencode($file); ?>" 
                                                   download class="btn btn-primary" style="padding: 6px 12px;">
                                                    📥 Download
                                                </a>
                                                <?php if ($can_restore): ?>
                                                <a href="?restore=<?php echo urlencode($file); ?>" 
                                                   class="btn btn-warning restore-btn" style="padding: 6px 12px;"
                                                   onclick="return confirm('⚠️ Restore from <?php echo htmlspecialchars($file); ?>?\n\nThis will overwrite current MySQL data!')">
                                                    🔄 Restore
                                                </a>
                                                <?php else: ?>
                                                <span class="btn btn-secondary" style="padding: 6px 12px; opacity: 0.7;" 
                                                      title="Only MySQL backups can be restored on this system">
                                                    🔄 Restore
                                                </span>
                                                <?php endif; ?>
                                                <a href="?delete=<?php echo urlencode($file); ?>" 
                                                   class="btn btn-danger" style="padding: 6px 12px;"
                                                   onclick="return confirm('Delete backup file: <?php echo htmlspecialchars($file); ?>?')">
                                                    🗑️ Delete
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <div style="text-align: center; padding: 40px; background: #f8f9fa; border-radius: 8px;">
                            <p style="color: #666; font-size: 1.1em;">No backup files found.</p>
                            <p style="color: #999; margin-top: 10px;">Create your first backup using the "Create Backup" tab.</p>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            
            <!-- Tab 4: Logs -->
            <div id="tab-logs" class="tab-content">
                <div class="card">
                    <h2>📋 Backup Logs</h2>
                    <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; max-height: 400px; overflow-y: auto;">
                        <?php
                        $log_files = [];
                        if (file_exists($logs_dir)) {
                            $logs = scandir($logs_dir);
                            foreach ($logs as $log) {
                                if ($log !== '.' && $log !== '..') {
                                    $log_files[] = $log;
                                }
                            }
                        }
                        
                        if (count($log_files) > 0): 
                            rsort($log_files); // Newest first
                        ?>
                            <?php foreach ($log_files as $log_file): 
                                $log_path = $logs_dir . $log_file;
                                $log_content = file_exists($log_path) ? file_get_contents($log_path) : '';
                            ?>
                                <div style="margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #ddd;">
                                    <strong><?php echo htmlspecialchars($log_file); ?></strong><br>
                                    <pre style="background: white; padding: 10px; border-radius: 5px; margin-top: 5px; font-size: 0.9em;"><?php echo htmlspecialchars($log_content); ?></pre>
                                </div>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <p style="color: #666; text-align: center;">No log files found.</p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            
            <!-- Backup Statistics -->
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-top: 40px;">
                <div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.08); text-align: center; border-top: 4px solid #0066ff;">
                    <p>📊 Total Backups</p>
                    <h3 style="font-size: 2.5em; margin: 10px 0; color: #0066ff;"><?php echo count($backup_files); ?></h3>
                </div>
                <div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.08); text-align: center; border-top: 4px solid #0066ff;">
                    <p>💾 Storage Used</p>
                    <h3 style="font-size: 2.5em; margin: 10px 0; color: #0066ff;">
                        <?php
                        $total_size = 0;
                        foreach ($backup_files as $file) {
                            $filepath = $db_backup_dir . $file;
                            if (file_exists($filepath)) {
                                $total_size += filesize($filepath);
                            }
                        }
                        echo formatBytes($total_size);
                        ?>
                    </h3>
                </div>
                <div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.08); text-align: center; border-top: 4px solid #4caf50;">
                    <p>✅ MySQL Backups</p>
                    <h3 style="font-size: 2.5em; margin: 10px 0; color: #4caf50;">
                        <?php echo count(array_filter($backup_files, function($f) { return strpos($f, '_mysql_') !== false; })); ?>
                    </h3>
                </div>
                <div style="background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.08); text-align: center; border-top: 4px solid #0066ff;">
                    <p>🔁 Can Restore</p>
                    <h3 style="font-size: 2.5em; margin: 10px 0; color: #0066ff;">MySQL Only</h3>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Tab switching
        function showTab(tabName) {
            // Hide all tabs
            document.querySelectorAll('.tab-content').forEach(tab => {
                tab.classList.remove('active');
            });
            
            // Remove active class from all tab buttons
            document.querySelectorAll('.tab').forEach(tab => {
                tab.classList.remove('active');
            });
            
            // Show selected tab
            document.getElementById('tab-' + tabName).classList.add('active');
            
            // Add active class to clicked tab button
            event.target.classList.add('active');
        }
        
        function updateDbStatus(selectedDb) {
            const statusText = document.getElementById('db-status-text');
            const dbStatus = {
                'mysql': '<?php echo $mysql_available ? "MySQL is available for backup & restore" : "MySQL is not connected"; ?>',
                'sqlserver': '<?php echo $sqlserver_available ? "SQL Server is available for backup only" : "SQL Server is not connected"; ?>',
                'postgresql': '<?php echo $postgresql_available ? "PostgreSQL is available for backup only" : "PostgreSQL is not connected"; ?>'
            };
            statusText.textContent = dbStatus[selectedDb] || 'Select a database';
        }
        
        function confirmRestore() {
            return confirm("⚠️ CRITICAL WARNING:\n\nThis will DELETE ALL current MySQL data and restore from backup!\n\nAre you ABSOLUTELY sure you want to continue?");
        }
        
        // Initialize
        document.addEventListener('DOMContentLoaded', function() {
            const select = document.querySelector('select[name="database_type"]');
            if (select) {
                updateDbStatus(select.value);
            }
        });
    </script>
</body>
</html>
<?php
// Helper function to format file sizes
function formatBytes($bytes, $precision = 2) {
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    
    return round($bytes, $precision) . ' ' . $units[$pow];
}
?>