<?php
session_start();
require_once 'connection.php';

// Check if user is NOT logged in. If not, redirect to login page.
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

$userRole = $_SESSION['role'] ?? 'Guest';
$username = $_SESSION['username'] ?? 'User';

// Create backup directories
$backup_dir = 'backups/';
$db_backup_dir = $backup_dir . 'database/';
$logs_dir = $backup_dir . 'logs/';

if (!file_exists($db_backup_dir)) {
    mkdir($db_backup_dir, 0777, true);
}
if (!file_exists($logs_dir)) {
    mkdir($logs_dir, 0777, true);
}

// Handle actions
$message = '';
$message_type = '';

// ⭐⭐⭐ ACTUAL BACKUP FUNCTION ⭐⭐⭐
function createDatabaseBackup() {
    global $conn, $db_backup_dir, $logs_dir, $username;
    
    $timestamp = date('Y-m-d_H-i-s');
    $backup_file = $db_backup_dir . "pharmacy_backup_" . $timestamp . ".sql";
    $log_file = $logs_dir . "backup_log_" . $timestamp . ".txt";
    
    try {
        // Get all tables from your database
        $tables = ['USER', 'PATIENT', 'MEDICINE', 'PRESCRIPTION', 'PRESCRIPTION_DETAIL'];
        $backup_content = "";
        
        $backup_content .= "-- Pharmacy Database Backup\n";
        $backup_content .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Generated by: " . $username . "\n";
        $backup_content .= "-- Database: PharmacyDB\n\n";
        
        $total_records = 0;
        
        foreach ($tables as $table) {
            $backup_content .= "-- Table: $table\n";
            
            // Get table data
            $query = "SELECT * FROM $table";
            $result = sqlsrv_query($conn, $query);
            
            if ($result) {
                while ($row = sqlsrv_fetch_array($result, SQLSRV_FETCH_ASSOC)) {
                    $columns = [];
                    $values = [];
                    
                    foreach ($row as $key => $value) {
                        $columns[] = $key;
                        // Handle NULL values and escape strings
                        if ($value === null) {
                            $values[] = 'NULL';
                        } else {
                            // Escape single quotes for SQL
                            $values[] = "'" . str_replace("'", "''", $value) . "'";
                        }
                    }
                    
                    $backup_content .= "INSERT INTO $table (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                    $total_records++;
                }
                sqlsrv_free_stmt($result);
            }
            $backup_content .= "\n";
        }
        
        // Save to file
        if (file_put_contents($backup_file, $backup_content)) {
            // Log success
            $log_message = "✅ Backup SUCCESS: " . date('Y-m-d H:i:s') . "\n";
            $log_message .= "User: " . $username . "\n";
            $log_message .= "File: " . basename($backup_file) . "\n";
            $log_message .= "Size: " . filesize($backup_file) . " bytes\n";
            $log_message .= "Tables backed up: " . count($tables) . "\n";
            $log_message .= "Total records: " . $total_records . "\n";
            
            file_put_contents($log_file, $log_message);
            
            return [
                'success' => true,
                'message' => "✅ <strong>ACTUAL DATABASE BACKUP CREATED!</strong><br>
                             File: <strong>" . basename($backup_file) . "</strong><br>
                             Size: " . filesize($backup_file) . " bytes<br>
                             Tables: " . count($tables) . "<br>
                             Records: " . $total_records,
                'file' => basename($backup_file)
            ];
        } else {
            return [
                'success' => false,
                'message' => "❌ Failed to write backup file."
            ];
        }
        
    } catch (Exception $e) {
        $error_log = "❌ Backup FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ Backup error: " . $e->getMessage()
        ];
    }
}

// Handle backup creation
if (isset($_POST['create_backup'])) {
    $result = createDatabaseBackup();
    $message = $result['message'];
    $message_type = $result['success'] ? 'success' : 'error';
}

// Handle file deletion
if (isset($_GET['delete'])) {
    $filename = $_GET['delete'];
    $filepath = $db_backup_dir . basename($filename);
    
    if (file_exists($filepath) && unlink($filepath)) {
        $message = "✅ Backup file deleted: " . htmlspecialchars($filename);
        $message_type = 'success';
    } else {
        $message = "❌ Failed to delete backup file.";
        $message_type = 'error';
    }
}

if (isset($_GET['action']) && $_GET['action'] == 'logs') {
    $message = "📋 Backup logs displayed below";
    $message_type = 'info';
}

if (isset($_GET['action']) && $_GET['action'] == 'auto') {
    $message = "⚙️ Auto backup settings loaded";
    $message_type = 'info';
}

// Get existing backup files
$backup_files = [];
if (file_exists($db_backup_dir)) {
    $files = scandir($db_backup_dir);
    foreach ($files as $file) {
        if ($file !== '.' && $file !== '..') {
            $backup_files[] = $file;
        }
    }
}

// Sort by date (newest first)
usort($backup_files, function($a, $b) use ($db_backup_dir) {
    $timeA = file_exists($db_backup_dir . $a) ? filemtime($db_backup_dir . $a) : 0;
    $timeB = file_exists($db_backup_dir . $b) ? filemtime($db_backup_dir . $b) : 0;
    return $timeB - $timeA; // Newest first
});
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Backup & Restore - Pharmacy System</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #0066ff 0%, #0099ff 100%); min-height: 100vh; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; background: white; border-radius: 15px; box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2); overflow: hidden; }
        
        .header { 
            background: linear-gradient(135deg, #0066ff 0%, #0099ff 100%); 
            color: white; 
            padding: 25px 30px; 
            text-align: center; 
        }
        .header h1 { font-size: 2em; margin: 0; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2); }
        
        .controls-top {
            padding: 20px 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: white;
            border-bottom: 1px solid #eee;
        }
        
        .btn {
            padding: 10px 20px;
            border-radius: 8px;
            border: none;
            cursor: pointer;
            font-size: 0.95em;
            font-weight: 500;
            transition: all 0.3s ease;
            text-decoration: none;
            display: inline-flex;
            align-items: center;
            gap: 8px;
        }
        .btn-primary { background: #0066ff; color: white; }
        .btn-secondary { background: #6c757d; color: white; }
        .btn-success { background: #28a745; color: white; }
        .btn-danger { background: #dc3545; color: white; }
        .btn-warning { background: #ffc107; color: #212529; }
        
        .btn:hover { transform: translateY(-2px); box-shadow: 0 5px 15px rgba(0,0,0,0.1); }
        
        .content { padding: 30px; }
        
        .backup-section {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 30px;
            margin-bottom: 40px;
        }
        
        @media (max-width: 768px) {
            .backup-section { grid-template-columns: 1fr; }
        }
        
        .card {
            background: white;
            border-radius: 10px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            padding: 25px;
            border-top: 4px solid #0066ff;
        }
        
        .card h2 {
            color: #0066ff;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        
        .form-group { margin-bottom: 20px; }
        .form-group label { display: block; margin-bottom: 8px; font-weight: 600; color: #333; }
        .form-control {
            width: 100%;
            padding: 10px 15px;
            border: 1px solid #ddd;
            border-radius: 6px;
            font-size: 1em;
        }
        
        .backup-files { margin-top: 30px; }
        
        .backup-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .backup-table th, .backup-table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        .backup-table th {
            background: #f8f9fa;
            color: #333;
            font-weight: 600;
        }
        .backup-table tr:hover { background: #f8f9fa; }
        
        .file-actions { display: flex; gap: 8px; }
        
        .message {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            animation: fadeIn 0.5s;
        }
        .message.success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .message.error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .message.info { background: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(-10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        .backup-stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .stat-card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.08);
            text-align: center;
            border-top: 4px solid #0066ff;
        }
        .stat-card h3 { font-size: 2.5em; margin: 10px 0; color: #0066ff; }
        .stat-card p { color: #666; font-size: 0.9em; }
        
        .tabs {
            display: flex;
            border-bottom: 1px solid #ddd;
            margin-bottom: 20px;
        }
        .tab {
            padding: 12px 24px;
            cursor: pointer;
            border-bottom: 3px solid transparent;
        }
        .tab.active {
            border-bottom: 3px solid #0066ff;
            color: #0066ff;
            font-weight: 600;
        }
        .tab-content { display: none; }
        .tab-content.active { display: block; }
    </style>
</head>
<body>
    <div class="container">
        <div class="controls-top">
            <div>
                <a href="dashboard.php" class="btn btn-secondary">← Back to Dashboard</a>
                <span style="margin-left: 20px; font-weight: 600;">
                    Logged in as: <strong><?php echo htmlspecialchars($username); ?></strong> (Role: <strong><?php echo htmlspecialchars($userRole); ?></strong>)
                </span>
            </div>
            <a href="logout.php" class="btn btn-secondary">Log Out</a>
        </div>
        
        <header class="header">
            <h1>💾 Backup & Restore System</h1>
            <p style="opacity: 0.9; margin-top: 10px;">Protect your pharmacy data with automated backups</p>
        </header>
        
        <div class="content">
            <?php if ($message): ?>
                <div class="message <?php echo $message_type; ?>">
                    <?php echo $message; ?>
                </div>
            <?php endif; ?>
            
            <!-- Tabs for different sections -->
            <div class="tabs" id="tabs">
                <div class="tab active" onclick="showTab('backup')">📥 Create Backup</div>
                <div class="tab" onclick="showTab('restore')">📤 Restore Backup</div>
                <div class="tab" onclick="showTab('files')">📁 Backup Files</div>
                <div class="tab" onclick="showTab('logs')">📋 Logs</div>
                <div class="tab" onclick="showTab('settings')">⚙️ Settings</div>
            </div>
            
            <!-- Tab 1: Create Backup -->
            <div id="tab-backup" class="tab-content active">
                <div class="card">
                    <h2>📥 Create New Backup</h2>
                    <form method="POST" action="">
                        <div class="form-group">
                            <label>Backup Name</label>
                            <input type="text" name="backup_name" class="form-control" 
                                   value="Pharmacy_Backup_<?php echo date('Y-m-d'); ?>" 
                                   placeholder="Enter backup name">
                        </div>
                        
                        <div class="form-group">
                            <label>Backup Type</label>
                            <select name="backup_type" class="form-control">
                                <option value="full">Full Database Backup</option>
                                <option value="inventory">Inventory Data Only</option>
                                <option value="prescriptions">Prescriptions Only</option>
                                <option value="sales">Sales Data Only</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label>Description (Optional)</label>
                            <textarea name="backup_desc" class="form-control" rows="3" 
                                      placeholder="Add notes about this backup..."></textarea>
                        </div>
                        
                        <button type="submit" name="create_backup" class="btn btn-primary" style="width: 100%; padding: 12px;">
                            🚀 Create Backup Now
                        </button>
                        
                        <p style="margin-top: 15px; font-size: 0.9em; color: #666; text-align: center;">
                            This will create an <strong>ACTUAL SQL BACKUP</strong> of your pharmacy database.
                        </p>
                    </form>
                </div>
            </div>
            
            <!-- Tab 2: Restore Backup -->
            <div id="tab-restore" class="tab-content">
                <div class="card">
                    <h2>📤 Restore from Backup</h2>
                    <form method="POST" action="" enctype="multipart/form-data">
                        <div class="form-group">
                            <label>Upload Backup File</label>
                            <input type="file" name="backup_file" class="form-control" accept=".sql,.txt,.backup">
                            <p style="font-size: 0.85em; color: #666; margin-top: 5px;">
                                Supported formats: .sql, .txt, .backup (Max: 10MB)
                            </p>
                        </div>
                        
                        <div style="background: #fff3cd; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
                            <strong>⚠️ Warning:</strong> Restoring will overwrite current data. 
                            Make sure you have a recent backup.
                        </div>
                        
                        <button type="submit" name="restore_backup" class="btn btn-warning" style="width: 100%; padding: 12px;">
                            🔄 Upload & Restore
                        </button>
                    </form>
                    
                    <div style="margin-top: 30px;">
                        <h3 style="color: #333; margin-bottom: 15px;">Or select from existing backups:</h3>
                        <?php if (count($backup_files) > 0): ?>
                            <select class="form-control" onchange="selectBackup(this.value)">
                                <option value="">Select a backup file...</option>
                                <?php foreach ($backup_files as $file): ?>
                                    <option value="<?php echo htmlspecialchars($file); ?>">
                                        <?php echo htmlspecialchars($file); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <button onclick="restoreSelected()" class="btn btn-success" style="margin-top: 15px; width: 100%; padding: 12px;">
                                📥 Restore Selected Backup
                            </button>
                        <?php else: ?>
                            <p style="color: #666; text-align: center; padding: 20px; background: #f8f9fa; border-radius: 8px;">
                                No backup files found.
                            </p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            
            <!-- Tab 3: Backup Files -->
            <div id="tab-files" class="tab-content">
                <div class="card">
                    <h2>📁 Existing Backup Files</h2>
                    
                    <?php if (count($backup_files) > 0): ?>
                        <table class="backup-table">
                            <thead>
                                <tr>
                                    <th>Filename</th>
                                    <th>Size</th>
                                    <th>Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($backup_files as $file): 
                                    $filepath = $db_backup_dir . $file;
                                    $filesize = file_exists($filepath) ? formatBytes(filesize($filepath)) : 'N/A';
                                    $filedate = file_exists($filepath) ? date('Y-m-d H:i', filemtime($filepath)) : 'N/A';
                                ?>
                                    <tr>
                                        <td><strong><?php echo htmlspecialchars($file); ?></strong></td>
                                        <td><?php echo $filesize; ?></td>
                                        <td><?php echo $filedate; ?></td>
                                        <td>
                                            <div class="file-actions">
                                                <a href="backups/database/<?php echo urlencode($file); ?>" 
                                                   download class="btn btn-primary" style="padding: 6px 12px;">
                                                    📥 Download
                                                </a>
                                                <button onclick="previewBackup('<?php echo htmlspecialchars($file); ?>')" 
                                                        class="btn btn-secondary" style="padding: 6px 12px;">
                                                    👁️ Preview
                                                </button>
                                                <a href="?delete=<?php echo urlencode($file); ?>" 
                                                   class="btn btn-danger" style="padding: 6px 12px;"
                                                   onclick="return confirm('Delete backup file: <?php echo htmlspecialchars($file); ?>?')">
                                                    🗑️ Delete
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <div style="text-align: center; padding: 40px; background: #f8f9fa; border-radius: 8px;">
                            <p style="color: #666; font-size: 1.1em;">No backup files found.</p>
                            <p style="color: #999; margin-top: 10px;">Create your first backup using the "Create Backup" tab.</p>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            
            <!-- Tab 4: Logs -->
            <div id="tab-logs" class="tab-content">
                <div class="card">
                    <h2>📋 Backup Logs</h2>
                    <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; max-height: 400px; overflow-y: auto;">
                        <?php
                        $log_files = [];
                        if (file_exists($logs_dir)) {
                            $logs = scandir($logs_dir);
                            foreach ($logs as $log) {
                                if ($log !== '.' && $log !== '..') {
                                    $log_files[] = $log;
                                }
                            }
                        }
                        
                        if (count($log_files) > 0): 
                            rsort($log_files); // Newest first
                        ?>
                            <?php foreach ($log_files as $log_file): 
                                $log_path = $logs_dir . $log_file;
                                $log_content = file_exists($log_path) ? file_get_contents($log_path) : '';
                            ?>
                                <div style="margin-bottom: 15px; padding-bottom: 15px; border-bottom: 1px solid #ddd;">
                                    <strong><?php echo htmlspecialchars($log_file); ?></strong><br>
                                    <pre style="background: white; padding: 10px; border-radius: 5px; margin-top: 5px; font-size: 0.9em;"><?php echo htmlspecialchars($log_content); ?></pre>
                                </div>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <p style="color: #666; text-align: center;">No log files found.</p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            
            <!-- Tab 5: Settings -->
            <div id="tab-settings" class="tab-content">
                <div class="card">
                    <h2>⚙️ Auto Backup Settings</h2>
                    <form method="POST" action="">
                        <div class="form-group">
                            <label>Enable Auto Backup</label>
                            <div>
                                <label style="display: inline-flex; align-items: center; margin-right: 20px;">
                                    <input type="radio" name="auto_backup" value="yes" checked> Yes
                                </label>
                                <label style="display: inline-flex; align-items: center;">
                                    <input type="radio" name="auto_backup" value="no"> No
                                </label>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label>Schedule</label>
                            <select name="schedule" class="form-control">
                                <option value="daily">Daily</option>
                                <option value="weekly">Weekly (Sunday)</option>
                                <option value="monthly">Monthly (1st of month)</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label>Backup Time</label>
                            <input type="time" name="backup_time" class="form-control" value="02:00">
                        </div>
                        
                        <div class="form-group">
                            <label>Keep Backups For</label>
                            <select name="retention" class="form-control">
                                <option value="7">7 days</option>
                                <option value="30" selected>30 days</option>
                                <option value="90">90 days</option>
                                <option value="365">1 year</option>
                            </select>
                        </div>
                        
                        <button type="submit" name="save_settings" class="btn btn-primary" style="width: 100%; padding: 12px;">
                            💾 Save Settings
                        </button>
                    </form>
                </div>
            </div>
            
            <!-- Backup Statistics -->
            <div class="backup-stats" style="margin-top: 40px;">
                <div class="stat-card">
                    <p>📊 Total Backups</p>
                    <h3><?php echo count($backup_files); ?></h3>
                </div>
                <div class="stat-card">
                    <p>💾 Storage Used</p>
                    <h3>
                        <?php
                        $total_size = 0;
                        foreach ($backup_files as $file) {
                            $filepath = $db_backup_dir . $file;
                            if (file_exists($filepath)) {
                                $total_size += filesize($filepath);
                            }
                        }
                        echo formatBytes($total_size);
                        ?>
                    </h3>
                </div>
                <div class="stat-card">
                    <p>📅 Last Backup</p>
                    <h3>
                        <?php 
                        if (count($backup_files) > 0) {
                            $latest = $backup_files[0];
                            $filepath = $db_backup_dir . $latest;
                            echo date('M d', file_exists($filepath) ? filemtime($filepath) : time());
                        } else {
                            echo 'Never';
                        }
                        ?>
                    </h3>
                </div>
                <div class="stat-card">
                    <p>✅ Status</p>
                    <h3 style="color: #28a745;">Ready</h3>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Tab switching
        function showTab(tabName) {
            // Hide all tabs
            document.querySelectorAll('.tab-content').forEach(tab => {
                tab.classList.remove('active');
            });
            
            // Remove active class from all tab buttons
            document.querySelectorAll('.tab').forEach(tab => {
                tab.classList.remove('active');
            });
            
            // Show selected tab
            document.getElementById('tab-' + tabName).classList.add('active');
            
            // Add active class to clicked tab button
            event.target.classList.add('active');
        }
        
        function selectBackup(filename) {
            console.log('Selected backup:', filename);
        }
        
        function restoreSelected() {
            const select = document.querySelector('select[onchange="selectBackup(this.value)"]');
            if (select.value) {
                if (confirm('⚠️ WARNING: This will overwrite current data!\n\nRestore from ' + select.value + '?')) {
                    alert('Restore process started for: ' + select.value + '\n\nThis is a demo. In real system, this would restore the database.');
                }
            } else {
                alert('Please select a backup file first.');
            }
        }
        
        function previewBackup(filename) {
            alert('Preview of backup file: ' + filename + '\n\nIn a real system, this would show the backup contents.');
        }
        
        // Auto-switch to requested tab
        <?php if (isset($_GET['action'])): ?>
            window.onload = function() {
                const action = '<?php echo $_GET["action"]; ?>';
                if (action === 'logs') showTab('logs');
                if (action === 'auto') showTab('settings');
            };
        <?php endif; ?>
    </script>
</body>
</html>

<?php
// Helper function to format file sizes
function formatBytes($bytes, $precision = 2) {
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    
    return round($bytes, $precision) . ' ' . $units[$pow];
}
?>