<?php
session_start();
require_once 'session_check.php'; // Add session check like other pages
require_once 'connection.php';

// Check if user is NOT logged in. If not, redirect to login page.
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

$userRole = $_SESSION['role'] ?? 'Guest';
$username = $_SESSION['username'] ?? 'User';

// Create backup directories
$backup_dir = 'backups/';
$db_backup_dir = $backup_dir . 'database/';
$logs_dir = $backup_dir . 'logs/';

if (!file_exists($db_backup_dir)) {
    mkdir($db_backup_dir, 0777, true);
}
if (!file_exists($logs_dir)) {
    mkdir($logs_dir, 0777, true);
}

// Handle actions
$message = '';
$message_type = '';

// ⭐⭐⭐ UNIVERSAL BACKUP FUNCTION (All 3 DBs) ⭐⭐⭐
function createDatabaseBackup($db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $timestamp = date('Y-m-d_H-i-s');
    $backup_file = $db_backup_dir . "pharmacy_backup_{$db_type}_" . $timestamp . ".sql";
    $log_file = $logs_dir . "backup_log_{$db_type}_" . $timestamp . ".txt";
    
    try {
        // Get all tables from your database
        $tables = ['USER', 'PATIENT', 'MEDICINE', 'PRESCRIPTION', 'PRESCRIPTION_DETAIL'];
        $backup_content = "";
        
        $backup_content .= "-- Pharmacy Database Backup ({$db_type})\n";
        $backup_content .= "-- Generated: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Generated by: " . $username . "\n";
        $backup_content .= "-- Database Type: " . strtoupper($db_type) . "\n\n";
        
        $total_records = 0;
        
        switch ($db_type) {
            case 'mysql':
                if (!$mysql_conn2) {
                    return ['success' => false, 'message' => "❌ MySQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $query = "SELECT * FROM `$table`";
                    $result = $mysql_conn2->query($query);
                    
                    if ($result && $result->num_rows > 0) {
                        while ($row = $result->fetch_assoc()) {
                            $columns = [];
                            $values = [];
                            
                            foreach ($row as $key => $value) {
                                $columns[] = $key;
                                if ($value === null) {
                                    $values[] = 'NULL';
                                } else {
                                    $values[] = "'" . $mysql_conn2->real_escape_string($value) . "'";
                                }
                            }
                            
                            $backup_content .= "INSERT INTO `$table` (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                            $total_records++;
                        }
                        $result->free();
                    }
                    $backup_content .= "\n";
                }
                break;
                
            case 'sqlserver':
                if (!$pdo) {
                    return ['success' => false, 'message' => "❌ SQL Server connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $stmt = $pdo->prepare("SELECT * FROM [$table]");
                    $stmt->execute();
                    
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                        $columns = [];
                        $values = [];
                        
                        foreach ($row as $key => $value) {
                            $columns[] = $key;
                            if ($value === null) {
                                $values[] = 'NULL';
                            } else {
                                $values[] = "'" . str_replace("'", "''", $value) . "'";
                            }
                        }
                        
                        $backup_content .= "INSERT INTO [$table] (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                        $total_records++;
                    }
                    $backup_content .= "\n";
                }
                break;
                
            case 'postgresql':
                if (!$pg_conn) {
                    return ['success' => false, 'message' => "❌ PostgreSQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $backup_content .= "-- Table: $table\n";
                    
                    $stmt = $pg_conn->prepare("SELECT * FROM \"$table\"");
                    $stmt->execute();
                    
                    while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                        $columns = [];
                        $values = [];
                        
                        foreach ($row as $key => $value) {
                            $columns[] = $key;
                            if ($value === null) {
                                $values[] = 'NULL';
                            } else {
                                $values[] = "'" . str_replace("'", "''", $value) . "'";
                            }
                        }
                        
                        $backup_content .= "INSERT INTO \"$table\" (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                        $total_records++;
                    }
                    $backup_content .= "\n";
                }
                break;
                
            default:
                return ['success' => false, 'message' => "❌ Unknown database type."];
        }
        
        // Save to file
        if (file_put_contents($backup_file, $backup_content)) {
            // Log success
            $log_message = "✅ {$db_type} Backup SUCCESS: " . date('Y-m-d H:i:s') . "\n";
            $log_message .= "User: " . $username . "\n";
            $log_message .= "File: " . basename($backup_file) . "\n";
            $log_message .= "Size: " . filesize($backup_file) . " bytes\n";
            $log_message .= "Tables backed up: " . count($tables) . "\n";
            $log_message .= "Total records: " . $total_records . "\n";
            
            file_put_contents($log_file, $log_message);
            
            return [
                'success' => true,
                'message' => "✅ <strong>" . strtoupper($db_type) . " BACKUP CREATED!</strong><br>
                             File: <strong>" . basename($backup_file) . "</strong><br>
                             Database: " . strtoupper($db_type) . "<br>
                             Size: " . filesize($backup_file) . " bytes<br>
                             Tables: " . count($tables) . "<br>
                             Records: " . $total_records,
                'file' => basename($backup_file),
                'db_type' => $db_type
            ];
        } else {
            return [
                'success' => false,
                'message' => "❌ Failed to write backup file."
            ];
        }
        
    } catch (Exception $e) {
        $error_log = "❌ {$db_type} Backup FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ {$db_type} backup error: " . $e->getMessage()
        ];
    }
}

// ⭐⭐⭐ EXCEL/CSV BACKUP FUNCTION (All 3 DBs) ⭐⭐⭐
function createExcelBackup($db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $timestamp = date('Y-m-d_H-i-s');
    $zip_file = $db_backup_dir . "pharmacy_excel_{$db_type}_" . $timestamp . ".zip";
    $log_file = $logs_dir . "excel_backup_log_{$db_type}_" . $timestamp . ".txt";
    
    try {
        $tables = ['USER', 'PATIENT', 'MEDICINE', 'PRESCRIPTION', 'PRESCRIPTION_DETAIL'];
        $total_records = 0;
        
        // Create ZIP file for all CSV files
        $zip = new ZipArchive();
        if ($zip->open($zip_file, ZipArchive::CREATE) !== TRUE) {
            throw new Exception("Cannot create ZIP file");
        }
        
        switch ($db_type) {
            case 'mysql':
                if (!$mysql_conn2) {
                    return ['success' => false, 'message' => "❌ MySQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $query = "SELECT * FROM `$table`";
                    $result = $mysql_conn2->query($query);
                    
                    if ($result && $result->num_rows > 0) {
                        $csv_content = "";
                        $rowData = $result->fetch_assoc();
                        $headers = array_keys($rowData);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        $result->data_seek(0);
                        while ($row = $result->fetch_assoc()) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                        $result->free();
                    }
                }
                break;
                
            case 'sqlserver':
                if (!$pdo) {
                    return ['success' => false, 'message' => "❌ SQL Server connection not available."];
                }
                
                foreach ($tables as $table) {
                    $stmt = $pdo->prepare("SELECT * FROM [$table]");
                    $stmt->execute();
                    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
                    
                    if ($rows) {
                        $csv_content = "";
                        $headers = array_keys($rows[0]);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        foreach ($rows as $row) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                    }
                }
                break;
                
            case 'postgresql':
                if (!$pg_conn) {
                    return ['success' => false, 'message' => "❌ PostgreSQL connection not available."];
                }
                
                foreach ($tables as $table) {
                    $stmt = $pg_conn->prepare("SELECT * FROM \"$table\"");
                    $stmt->execute();
                    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
                    
                    if ($rows) {
                        $csv_content = "";
                        $headers = array_keys($rows[0]);
                        $csv_content .= '"' . implode('","', $headers) . '"' . "\n";
                        
                        foreach ($rows as $row) {
                            $escaped_row = array_map(function($value) {
                                if ($value === null) return '';
                                return str_replace('"', '""', $value);
                            }, $row);
                            
                            $csv_content .= '"' . implode('","', $escaped_row) . '"' . "\n";
                            $total_records++;
                        }
                        
                        $zip->addFromString("{$table}.csv", $csv_content);
                    }
                }
                break;
        }
        
        $zip->close();
        
        // Log success
        $log_message = "✅ {$db_type} Excel Backup SUCCESS: " . date('Y-m-d H:i:s') . "\n";
        $log_message .= "User: " . $username . "\n";
        $log_message .= "File: " . basename($zip_file) . "\n";
        $log_message .= "Size: " . filesize($zip_file) . " bytes\n";
        $log_message .= "Tables backed up: " . count($tables) . "\n";
        $log_message .= "Total records: " . $total_records . "\n";
        
        file_put_contents($log_file, $log_message);
        
        return [
            'success' => true,
            'message' => "✅ <strong>" . strtoupper($db_type) . " EXCEL BACKUP CREATED!</strong><br>
                         File: <strong>" . basename($zip_file) . "</strong><br>
                         Format: ZIP with CSV files<br>
                         Database: " . strtoupper($db_type) . "<br>
                         Size: " . filesize($zip_file) . " bytes<br>
                         Tables: " . count($tables) . "<br>
                         Records: " . $total_records,
            'file' => basename($zip_file),
            'db_type' => $db_type
        ];
        
    } catch (Exception $e) {
        $error_log = "❌ {$db_type} Excel Backup FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ {$db_type} Excel backup error: " . $e->getMessage()
        ];
    }
}

// ⭐⭐⭐ RESTORE DATABASE FUNCTION ⭐⭐⭐
function restoreDatabase($backup_file, $db_type) {
    global $pdo, $mysql_conn2, $pg_conn, $db_backup_dir, $logs_dir, $username;
    
    $full_path = $db_backup_dir . $backup_file;
    $log_file = $logs_dir . 'restore_log_' . date('Y-m-d_H-i-s') . '.txt';
    
    if (!file_exists($full_path)) {
        return ['success' => false, 'message' => '❌ Backup file not found'];
    }
    
    try {
        $file_ext = strtolower(pathinfo($backup_file, PATHINFO_EXTENSION));
        
        // Log start
        $log_content = "🔧 RESTORE STARTED: " . date('Y-m-d H:i:s') . "\n";
        $log_content .= "User: " . $username . "\n";
        $log_content .= "File: " . $backup_file . "\n";
        $log_content .= "Database: " . strtoupper($db_type) . "\n";
        $log_content .= "File Size: " . filesize($full_path) . " bytes\n\n";
        
        $success = false;
        $records_restored = 0;
        $errors = [];
        
        if ($file_ext === 'sql') {
            // SQL file restore
            $sql_content = file_get_contents($full_path);
            $queries = array_filter(array_map('trim', explode(';', $sql_content)));
            
            if ($db_type === 'mysql' && $mysql_conn2) {
                // Begin transaction
                $mysql_conn2->begin_transaction();
                
                // Temporarily disable foreign key checks
                $mysql_conn2->query("SET FOREIGN_KEY_CHECKS = 0");
                
                // Clear existing data (WARNING: This deletes all data!)
                $tables = ['PRESCRIPTION_DETAIL', 'PRESCRIPTION', 'MEDICINE', 'PATIENT', 'USER'];
                foreach ($tables as $table) {
                    $mysql_conn2->query("DELETE FROM `$table`");
                    $mysql_conn2->query("ALTER TABLE `$table` AUTO_INCREMENT = 1");
                }
                
                // Execute INSERT queries only
                foreach ($queries as $query) {
                    if (!empty($query) && stripos($query, 'INSERT') === 0) {
                        if ($mysql_conn2->query($query)) {
                            $records_restored += $mysql_conn2->affected_rows;
                        } else {
                            $errors[] = "MySQL Error: " . $mysql_conn2->error;
                        }
                    }
                }
                
                $mysql_conn2->query("SET FOREIGN_KEY_CHECKS = 1");
                $mysql_conn2->commit();
                $success = true;
            } else {
                $errors[] = "Only MySQL restoration is currently supported";
            }
        } elseif ($file_ext === 'zip') {
            $errors[] = "CSV/ZIP restoration not yet implemented. Please use SQL files.";
        }
        
        // Log results
        if ($success) {
            $log_content .= "✅ RESTORE COMPLETED SUCCESSFULLY\n";
            $log_content .= "Records restored: " . $records_restored . "\n";
            $log_content .= "Errors: " . count($errors) . "\n";
            
            if (!empty($errors)) {
                $log_content .= "\nERROR DETAILS:\n" . implode("\n", $errors) . "\n";
            }
            
            file_put_contents($log_file, $log_content);
            
            return [
                'success' => true,
                'message' => "✅ <strong>DATABASE RESTORED SUCCESSFULLY!</strong><br>
                             File: <strong>" . $backup_file . "</strong><br>
                             Database: " . strtoupper($db_type) . "<br>
                             Records restored: " . $records_restored . "<br>
                             Time: " . date('H:i:s')
            ];
        } else {
            $log_content .= "❌ RESTORE FAILED\n";
            $log_content .= "Errors: " . implode(", ", $errors) . "\n";
            file_put_contents($log_file, $log_content);
            
            return [
                'success' => false,
                'message' => "❌ Restore failed: " . implode(", ", $errors)
            ];
        }
        
    } catch (Exception $e) {
        $error_log = "❌ RESTORE FAILED: " . date('Y-m-d H:i:s') . "\n";
        $error_log .= "Error: " . $e->getMessage() . "\n";
        file_put_contents($logs_dir . "restore_error_log.txt", $error_log, FILE_APPEND);
        
        return [
            'success' => false,
            'message' => "❌ Restore error: " . $e->getMessage()
        ];
    }
}

// Handle backup creation
if (isset($_POST['create_backup'])) {
    $db_type = $_POST['database_type'] ?? 'mysql';
    $format = $_POST['backup_format'] ?? 'sql';
    
    if ($format === 'excel') {
        $result = createExcelBackup($db_type);
    } else {
        $result = createDatabaseBackup($db_type);
    }
    
    $message = $result['message'];
    $message_type = $result['success'] ? 'success' : 'error';
}

// Handle restore action
if (isset($_POST['restore_backup'])) {
    $backup_file = $_POST['backup_file'] ?? '';
    $database_type = $_POST['database_type'] ?? 'mysql';
    $confirmation = $_POST['confirmation'] ?? '';
    
    if (empty($backup_file)) {
        $message = '❌ Please select a backup file';
        $message_type = 'error';
    } elseif ($confirmation !== 'YES') {
        $message = '❌ You must type YES to confirm restoration';
        $message_type = 'error';
    } else {
        $result = restoreDatabase($backup_file, $database_type);
        $message = $result['message'];
        $message_type = $result['success'] ? 'success' : 'error';
    }
}

// Handle file upload for restore
if (isset($_POST['upload_restore'])) {
    if (isset($_FILES['backup_file']) && $_FILES['backup_file']['error'] === UPLOAD_ERR_OK) {
        $file_tmp = $_FILES['backup_file']['tmp_name'];
        $file_name = basename($_FILES['backup_file']['name']);
        $file_ext = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));
        
        // Validate file type
        if ($file_ext === 'sql' || $file_ext === 'zip') {
            $new_filename = 'uploaded_' . date('Y-m-d_H-i-s') . '_' . $file_name;
            $destination = $db_backup_dir . $new_filename;
            
            if (move_uploaded_file($file_tmp, $destination)) {
                $message = '✅ File uploaded successfully. You can now restore from it.';
                $message_type = 'success';
            } else {
                $message = '❌ Failed to upload file';
                $message_type = 'error';
            }
        } else {
            $message = '❌ Invalid file type. Only .sql or .zip files allowed';
            $message_type = 'error';
        }
    } else {
        $message = '❌ Please select a file to upload';
        $message_type = 'error';
    }
}

// Handle file deletion
if (isset($_GET['delete'])) {
    $file_to_delete = $_GET['delete'];
    $file_path = $db_backup_dir . $file_to_delete;
    
    if (file_exists($file_path)) {
        if (unlink($file_path)) {
            $message = '✅ Backup file deleted successfully';
            $message_type = 'success';
        } else {
            $message = '❌ Failed to delete file';
            $message_type = 'error';
        }
    }
}

// Get existing backup files
$backup_files = [];
if (file_exists($db_backup_dir)) {
    $files = scandir($db_backup_dir);
    foreach ($files as $file) {
        if ($file !== '.' && $file !== '..') {
            $backup_files[] = $file;
        }
    }
}

// Sort by date (newest first)
usort($backup_files, function($a, $b) use ($db_backup_dir) {
    $timeA = file_exists($db_backup_dir . $a) ? filemtime($db_backup_dir . $a) : 0;
    $timeB = file_exists($db_backup_dir . $b) ? filemtime($db_backup_dir . $b) : 0;
    return $timeB - $timeA; // Newest first
});

// Check which databases are available
$mysql_available = ($mysql_conn2 && $mysql_conn2 instanceof mysqli);
$sqlserver_available = (isset($pdo) && $pdo instanceof PDO);
$postgresql_available = (isset($pg_conn) && $pg_conn instanceof PDO);

// Calculate backup stats
$total_size = 0;
foreach ($backup_files as $file) {
    $filepath = $db_backup_dir . $file;
    if (file_exists($filepath)) {
        $total_size += filesize($filepath);
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PharmaCare - Backup & Restore System</title>
    <style>
        /* ===== DASHBOARD THEME STYLES ===== */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #0d1b4e 0%, #1a2980 30%, #26d0ce 100%);
            background-attachment: fixed;
            color: #333;
            min-height: 100vh;
            padding-top: 100px; /* Space for fixed menu */
        }
        
        a {
            text-decoration: none;
            color: inherit;
        }
        
        /* ===== OVAL NAVIGATION MENU ===== */
        .oval-nav-container {
            position: fixed;
            top: 20px;
            left: 50%;
            transform: translateX(-50%);
            z-index: 1000;
            width: auto;
            transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
        }
        
        .oval-nav-container.scrolled {
            top: 10px;
            transform: translateX(-50%) scale(0.95);
        }
        
        .oval-nav {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(15px);
            border-radius: 50px;
            padding: 8px 25px;
            box-shadow: 0 10px 30px rgba(0, 0, 100, 0.2);
            border: 1px solid rgba(255, 255, 255, 0.3);
            display: flex;
            align-items: center;
            justify-content: center;
            transition: all 0.3s ease;
        }
        
        .oval-nav.scrolled {
            padding: 6px 20px;
            background: rgba(255, 255, 255, 0.98);
            box-shadow: 0 8px 25px rgba(0, 0, 100, 0.15);
        }
        
        /* ===== NAVIGATION MENU ===== */
        .nav-menu {
            display: flex;
            list-style: none;
            gap: 2px;
            margin: 0;
            padding: 0;
        }
        
        .nav-item {
            position: relative;
        }
        
        .nav-link {
            display: flex;
            align-items: center;
            gap: 8px;
            padding: 12px 16px;
            color: #1a2980;
            font-weight: 600;
            font-size: 13px;
            transition: all 0.3s ease;
            border-radius: 30px;
            white-space: nowrap;
        }
        
        .nav-link:hover {
            background: linear-gradient(135deg, rgba(26, 41, 128, 0.1) 0%, rgba(38, 208, 206, 0.1) 100%);
            color: #1a2980;
            transform: translateY(-1px);
        }
        
        .nav-link i {
            color: #26d0ce;
            font-size: 14px;
            width: 18px;
            text-align: center;
        }
        
        /* ===== DROPDOWN MENUS ===== */
        .dropdown-menu {
            position: absolute;
            top: 100%;
            left: 0;
            background: white;
            min-width: 230px;
            box-shadow: 0 15px 35px rgba(0, 0, 100, 0.2);
            border-radius: 15px;
            opacity: 0;
            visibility: hidden;
            transform: translateY(-15px) scale(0.95);
            transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
            z-index: 1000;
            border: 1px solid rgba(26, 41, 128, 0.1);
            overflow: hidden;
            margin-top: 10px;
        }
        
        .nav-item:hover .dropdown-menu {
            opacity: 1;
            visibility: visible;
            transform: translateY(0) scale(1);
        }
        
        .dropdown-header {
            padding: 12px 18px;
            background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%);
            color: white;
            font-weight: 600;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .dropdown-item {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 12px 18px;
            color: #555;
            border-bottom: 1px solid #f0f7ff;
            transition: all 0.2s ease;
            font-size: 13px;
        }
        
        .dropdown-item:hover {
            background: linear-gradient(135deg, #f9fbff 0%, #e6f0ff 100%);
            color: #1a2980;
            padding-left: 22px;
            border-left: 3px solid #26d0ce;
        }
        
        .dropdown-item i {
            color: #26d0ce;
            width: 16px;
            font-size: 13px;
        }
        
        /* ===== USER SECTION ===== */
        .user-section {
            display: flex;
            align-items: center;
            gap: 10px;
            margin-left: 20px;
            padding-left: 20px;
            border-left: 1px solid rgba(26, 41, 128, 0.2);
        }
        
        .user-badge {
            background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%);
            color: white;
            padding: 8px 16px;
            border-radius: 25px;
            font-weight: 600;
            font-size: 12px;
            box-shadow: 0 4px 12px rgba(26, 41, 128, 0.2);
            display: flex;
            align-items: center;
            gap: 7px;
            white-space: nowrap;
        }
        
        .logout-btn {
            background: #ffeaea;
            color: #d32f2f;
            border: none;
            padding: 8px 16px;
            border-radius: 25px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s ease;
            display: flex;
            align-items: center;
            gap: 5px;
            font-size: 12px;
            white-space: nowrap;
        }
        
        .logout-btn:hover {
            background: #ffcccc;
            transform: translateY(-1px);
            box-shadow: 0 4px 12px rgba(211, 47, 47, 0.3);
        }
        
        /* ===== PAGE HEADER ===== */
        .page-header {
            text-align: center;
            padding: 30px 20px 20px;
            margin-bottom: 30px;
        }
        
        .page-title {
            font-size: 2.5rem;
            font-weight: 800;
            margin-bottom: 10px;
            color: white;
            text-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
            line-height: 1.1;
        }
        
        .page-subtitle {
            font-size: 1.1rem;
            color: rgba(255, 255, 255, 0.85);
            font-weight: 300;
            letter-spacing: 0.5px;
            max-width: 600px;
            margin: 0 auto;
        }
        
        /* ===== MAIN CONTENT ===== */
        .main-content {
            padding: 0 30px 40px;
        }
        
        /* ===== DATABASE STATUS CARDS ===== */
        .status-container {
            display: flex;
            justify-content: center;
            margin-bottom: 40px;
        }
        
        .status-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            max-width: 1300px;
            width: 100%;
        }
        
        .status-card {
            background: rgba(255, 255, 255, 0.95);
            border-radius: 15px;
            padding: 25px 20px;
            text-align: center;
            box-shadow: 0 6px 18px rgba(0, 0, 100, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
            transition: all 0.3s ease;
            position: relative;
            overflow: hidden;
        }
        
        .status-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 4px;
            background: linear-gradient(90deg, #1a2980 0%, #26d0ce 100%);
            border-radius: 15px 15px 0 0;
        }
        
        .status-card:hover {
            transform: translateY(-5px);
            background: white;
            box-shadow: 0 15px 35px rgba(0, 0, 100, 0.2);
        }
        
        .status-icon {
            width: 60px;
            height: 60px;
            border-radius: 15px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 24px;
            margin: 0 auto 15px;
            background: linear-gradient(135deg, rgba(26, 41, 128, 0.1) 0%, rgba(38, 208, 206, 0.1) 100%);
            color: #1a2980;
            transition: all 0.25s ease;
        }
        
        .status-card:hover .status-icon {
            transform: scale(1.1);
            background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%);
            color: white;
        }
        
        .status-name {
            font-size: 20px;
            font-weight: 700;
            margin-bottom: 10px;
            color: #1a2980;
        }
        
        .status-indicator {
            display: inline-flex;
            align-items: center;
            gap: 5px;
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
            margin-bottom: 10px;
        }
        
        .status-online {
            background: rgba(76, 175, 80, 0.15);
            color: #2e7d32;
            border: 1px solid rgba(76, 175, 80, 0.2);
        }
        
        .status-offline {
            background: rgba(244, 67, 54, 0.15);
            color: #c62828;
            border: 1px solid rgba(244, 67, 54, 0.2);
        }
        
        .status-dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            display: inline-block;
        }
        
        .dot-online {
            background: #4CAF50;
        }
        
        .dot-offline {
            background: #f44336;
        }
        
        .status-description {
            color: #666;
            font-size: 13px;
        }
        
        /* ===== BACKUP CONTROL PANEL ===== */
        .backup-container {
            max-width: 1300px;
            margin: 0 auto;
            background: rgba(255, 255, 255, 0.95);
            border-radius: 15px;
            padding: 30px;
            box-shadow: 0 6px 18px rgba(0, 0, 100, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }
        
        /* ===== MESSAGE ALERT ===== */
        .alert-message {
            background: white;
            border-radius: 10px;
            padding: 15px 20px;
            margin-bottom: 25px;
            border-left: 4px solid #26d0ce;
            box-shadow: 0 4px 15px rgba(0, 0, 100, 0.08);
            font-weight: 500;
        }
        
        .alert-success {
            border-left-color: #4CAF50;
            background: rgba(76, 175, 80, 0.05);
        }
        
        .alert-error {
            border-left-color: #f44336;
            background: rgba(244, 67, 54, 0.05);
        }
        
        /* ===== TAB STYLES ===== */
        .tab-navigation {
            display: flex;
            border-bottom: 2px solid rgba(26, 41, 128, 0.1);
            margin-bottom: 30px;
            overflow-x: auto;
        }
        
        .tab-button {
            padding: 12px 25px;
            background: none;
            border: none;
            font-weight: 600;
            color: #666;
            cursor: pointer;
            transition: all 0.3s ease;
            border-bottom: 3px solid transparent;
            white-space: nowrap;
            display: flex;
            align-items: center;
            gap: 8px;
        }
        
        .tab-button:hover {
            color: #1a2980;
        }
        
        .tab-button.active {
            color: #1a2980;
            border-bottom: 3px solid #26d0ce;
        }
        
        .tab-content {
            display: none;
            animation: fadeIn 0.5s ease;
        }
        
        .tab-content.active {
            display: block;
        }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        /* ===== BACKUP FORM ===== */
        .backup-form {
            background: white;
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0 4px 15px rgba(0, 0, 100, 0.08);
            margin-bottom: 30px;
        }
        
        .form-group {
            margin-bottom: 25px;
        }
        
        .form-label {
            display: block;
            margin-bottom: 8px;
            color: #1a2980;
            font-weight: 600;
            font-size: 14px;
        }
        
        .form-control {
            width: 100%;
            padding: 12px 15px;
            border: 2px solid rgba(26, 41, 128, 0.1);
            border-radius: 8px;
            font-size: 14px;
            transition: all 0.3s ease;
        }
        
        .form-control:focus {
            border-color: #26d0ce;
            box-shadow: 0 0 0 3px rgba(38, 208, 206, 0.2);
            outline: none;
        }
        
        /* ===== FORMAT CARDS ===== */
        .format-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin: 20px 0;
        }
        
        .format-card {
            border-radius: 10px;
            padding: 20px;
            transition: all 0.3s ease;
            cursor: pointer;
            border: 2px solid transparent;
        }
        
        .format-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 25px rgba(0, 0, 100, 0.15);
        }
        
        .format-card.selected {
            border-color: #26d0ce;
            background: linear-gradient(135deg, #f9fbff 0%, #e6f0ff 100%);
        }
        
        .format-card.sql {
            background: rgba(26, 41, 128, 0.05);
            border: 2px solid rgba(26, 41, 128, 0.2);
        }
        
        .format-card.excel {
            background: rgba(38, 208, 206, 0.05);
            border: 2px solid rgba(38, 208, 206, 0.2);
        }
        
        .format-icon {
            font-size: 24px;
            margin-bottom: 10px;
        }
        
        .format-card.sql .format-icon {
            color: #1a2980;
        }
        
        .format-card.excel .format-icon {
            color: #26d0ce;
        }
        
        .format-title {
            font-weight: 700;
            margin-bottom: 10px;
            color: #1a2980;
        }
        
        .format-features {
            list-style: none;
        }
        
        .format-features li {
            padding: 5px 0;
            color: #666;
            font-size: 13px;
            display: flex;
            align-items: center;
            gap: 8px;
        }
        
        .format-features li:before {
            content: '✓';
            color: #26d0ce;
            font-weight: bold;
        }
        
        /* ===== BUTTONS ===== */
        .btn-backup {
            background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%);
            color: white;
            border: none;
            padding: 15px 30px;
            border-radius: 10px;
            font-weight: 600;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s ease;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
            width: 100%;
        }
        
        .btn-backup:hover {
            transform: translateY(-3px);
            box-shadow: 0 10px 25px rgba(26, 41, 128, 0.3);
        }
        
        .btn-danger {
            background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
            color: white;
            border: none;
            padding: 15px 30px;
            border-radius: 10px;
            font-weight: 600;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s ease;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
            width: 100%;
        }
        
        .btn-danger:hover {
            transform: translateY(-3px);
            box-shadow: 0 10px 25px rgba(220, 53, 69, 0.3);
        }
        
        /* ===== BACKUP FILES TABLE ===== */
        .files-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background: white;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 4px 15px rgba(0, 0, 100, 0.08);
        }
        
        .files-table thead {
            background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%);
            color: white;
        }
        
        .files-table th {
            padding: 15px;
            text-align: left;
            font-weight: 600;
            font-size: 14px;
            border: none;
        }
        
        .files-table td {
            padding: 15px;
            border-bottom: 1px solid rgba(26, 41, 128, 0.1);
            font-size: 13px;
        }
        
        .files-table tbody tr {
            transition: all 0.2s ease;
        }
        
        .files-table tbody tr:hover {
            background: linear-gradient(135deg, #f9fbff 0%, #e6f0ff 100%);
        }
        
        /* ===== BADGES ===== */
        .file-badge {
            display: inline-flex;
            align-items: center;
            gap: 5px;
            padding: 4px 10px;
            border-radius: 15px;
            font-size: 11px;
            font-weight: 600;
            color: white;
        }
        
        .badge-mysql {
            background: linear-gradient(135deg, #4CAF50 0%, #2e7d32 100%);
        }
        
        .badge-sqlserver {
            background: linear-gradient(135deg, #2196F3 0%, #0d47a1 100%);
        }
        
        .badge-postgresql {
            background: linear-gradient(135deg, #673AB7 0%, #311b92 100%);
        }
        
        .badge-format {
            background: linear-gradient(135deg, #FF9800 0%, #ef6c00 100%);
        }
        
        /* ===== ACTION BUTTONS ===== */
        .action-buttons {
            display: flex;
            gap: 8px;
        }
        
        .btn-action {
            padding: 8px 15px;
            border-radius: 6px;
            font-size: 12px;
            font-weight: 600;
            border: none;
            cursor: pointer;
            transition: all 0.2s ease;
            display: inline-flex;
            align-items: center;
            gap: 5px;
            text-decoration: none;
        }
        
        .btn-download {
            background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%);
            color: white;
        }
        
        .btn-delete {
            background: linear-gradient(135deg, #f44336 0%, #c62828 100%);
            color: white;
        }
        
        .btn-action:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
        }
        
        /* ===== STATS CARDS ===== */
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
            margin: 40px 0;
        }
        
        .stat-card {
            background: rgba(255, 255, 255, 0.95);
            border-radius: 15px;
            padding: 25px 20px;
            text-align: center;
            box-shadow: 0 6px 18px rgba(0, 0, 100, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.2);
            transition: all 0.3s ease;
        }
        
        .stat-card:hover {
            transform: translateY(-5px);
            background: white;
            box-shadow: 0 15px 35px rgba(0, 0, 100, 0.2);
        }
        
        .stat-value {
            font-size: 42px;
            font-weight: 800;
            margin-bottom: 5px;
            color: #1a2980;
            line-height: 1;
            background: linear-gradient(135deg, #1a2980 0%, #26d0ce 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        
        .stat-label {
            color: #666;
            font-size: 15px;
            font-weight: 600;
        }
        
        /* ===== RESTORE WARNING ===== */
        .restore-warning {
            background: linear-gradient(135deg, #fff3cd 0%, #ffeaa7 100%);
            border-left: 4px solid #ffc107;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 25px;
        }
        
        .restore-warning h4 {
            color: #856404;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        
        .confirmation-input {
            border: 2px solid #dc3545 !important;
            font-weight: bold;
            text-align: center;
            letter-spacing: 2px;
        }
        
        /* ===== UPLOAD AREA ===== */
        .upload-area {
            border: 2px dashed #26d0ce;
            border-radius: 10px;
            padding: 40px;
            text-align: center;
            margin: 20px 0;
            background: rgba(38, 208, 206, 0.05);
            transition: all 0.3s ease;
            cursor: pointer;
        }
        
        .upload-area:hover {
            background: rgba(38, 208, 206, 0.1);
            border-color: #1a2980;
        }
        
        /* ===== RESPONSIVE DESIGN ===== */
        @media (max-width: 1200px) {
            .status-grid,
            .stats-grid {
                grid-template-columns: repeat(2, 1fr);
                max-width: 850px;
                gap: 20px;
            }
            
            .format-grid {
                grid-template-columns: 1fr;
            }
            
            .page-title {
                font-size: 2.2rem;
            }
        }
        
        @media (max-width: 992px) {
            body {
                padding-top: 140px;
            }
            
            .oval-nav-container {
                width: calc(100% - 40px);
                max-width: 600px;
            }
            
            .oval-nav {
                padding: 15px;
                flex-direction: column;
                border-radius: 25px;
            }
            
            .nav-menu {
                flex-direction: column;
                width: 100%;
                gap: 5px;
                margin-bottom: 15px;
            }
            
            .dropdown-menu {
                position: static;
                opacity: 1;
                visibility: visible;
                transform: none;
                box-shadow: none;
                border-radius: 10px;
                background: #f9f9f9;
                border: none;
                display: none;
                margin: 10px 0;
            }
            
            .nav-item.active .dropdown-menu {
                display: block;
            }
            
            .user-section {
                margin-left: 0;
                padding-left: 0;
                border-left: none;
                border-top: 1px solid rgba(26, 41, 128, 0.2);
                padding-top: 15px;
                margin-top: 15px;
                width: 100%;
                justify-content: center;
            }
            
            .main-content {
                padding: 0 20px 30px;
            }
            
            .tab-navigation {
                flex-wrap: nowrap;
                overflow-x: auto;
            }
        }
        
        @media (max-width: 768px) {
            .status-grid,
            .stats-grid {
                grid-template-columns: 1fr;
                max-width: 400px;
                gap: 15px;
            }
            
            .files-table {
                display: block;
                overflow-x: auto;
            }
            
            .page-title {
                font-size: 1.8rem;
            }
            
            .page-subtitle {
                font-size: 0.9rem;
            }
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Segoe+UI:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
</head>
<body>
    <!-- OVAL NAVIGATION MENU -->
    <div class="oval-nav-container" id="ovalNav">
        <nav class="oval-nav" id="ovalNavInner">
            <!-- NAVIGATION MENU -->
            <ul class="nav-menu" id="navMenu">
                <!-- DASHBOARD -->
                <li class="nav-item">
                    <a href="dashboard.php" class="nav-link">
                        <i class="fas fa-tachometer-alt"></i> Dashboard
                    </a>
                </li>
                
                <!-- INVENTORY MANAGEMENT -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-warehouse"></i> Inventory
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-header">Inventory Management</div>
                        <a href="medDirectory.php" class="dropdown-item">
                            <i class="fas fa-list-alt"></i> Medicine List
                        </a>
                        <a href="inventory.php" class="dropdown-item">
                            <i class="fas fa-boxes"></i> Stock Management
                        </a>
                        <a href="low_stock.php" class="dropdown-item">
                            <i class="fas fa-exclamation-triangle"></i> Low Stock Alert
                        </a>
                    </div>
                </li>
                
                <!-- PRESCRIPTION MANAGEMENT -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-file-medical"></i> Prescriptions
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-header">Prescription Management</div>
                        <a href="prescriptionDashboard.php" class="dropdown-item">
                            <i class="fas fa-tachometer-alt"></i> Dashboard
                        </a>
                        <a href="add_prescription.php" class="dropdown-item">
                            <i class="fas fa-plus-circle"></i> New Prescription
                        </a>
                        <a href="prescription_history.php" class="dropdown-item">
                            <i class="fas fa-history"></i> History
                        </a>
                    </div>
                </li>
                
                <!-- SALES & BILLING -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-cash-register"></i> Sales
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-header">Sales & Billing</div>
                        <a href="Sales_Billing.php" class="dropdown-item">
                            <i class="fas fa-chart-line"></i> Dashboard
                        </a>
                        <a href="new_sale.php" class="dropdown-item">
                            <i class="fas fa-shopping-cart"></i> New Sale
                        </a>
                        <a href="invoice_history.php" class="dropdown-item">
                            <i class="fas fa-file-invoice-dollar"></i> Invoice History
                        </a>
                    </div>
                </li>
                
                <!-- REPORTS & ANALYTICS -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-chart-line"></i> Reports
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-header">Reports & Analytics</div>
                        <a href="reports.php" class="dropdown-item">
                            <i class="fas fa-chart-bar"></i> Analytics Dashboard
                        </a>
                        <a href="sales_report.php" class="dropdown-item">
                            <i class="fas fa-chart-pie"></i> Sales Reports
                        </a>
                        <a href="inventory_report.php" class="dropdown-item">
                            <i class="fas fa-chart-area"></i> Inventory Reports
                        </a>
                    </div>
                </li>
                
                <!-- BACKUP & RESTORE (Active) -->
                <li class="nav-item">
                    <a href="backup.php" class="nav-link" style="background: linear-gradient(135deg, rgba(26, 41, 128, 0.1) 0%, rgba(38, 208, 206, 0.1) 100%);">
                        <i class="fas fa-database"></i> Backup
                    </a>
                    <div class="dropdown-menu">
                        <div class="dropdown-header">Backup & Restore</div>
                        <a href="backup.php" class="dropdown-item" style="background: #f9fbff; border-left: 3px solid #26d0ce;">
                            <i class="fas fa-database"></i> Backup & Restore System
                        </a>
                        <div class="dropdown-item" style="background: #f9fbff; border-left: 3px solid #26d0ce; margin: 6px; border-radius: 10px; padding: 12px;">
                            <div style="font-size: 12px; color: #666;">
                                <p style="margin-bottom: 6px; display: flex; align-items: center; gap: 6px;">
                                    <i class="fas fa-check-circle" style="color: #26d0ce;"></i> SQL + Excel formats
                                </p>
                                <p style="margin-bottom: 6px; display: flex; align-items: center; gap: 6px;">
                                    <i class="fas fa-check-circle" style="color: #26d0ce;"></i> Multi-database support
                                </p>
                                <p style="display: flex; align-items: center; gap: 6px;">
                                    <i class="fas fa-check-circle" style="color: #26d0ce;"></i> Full restore functionality
                                </p>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
            
            <!-- USER SECTION -->
            <div class="user-section">
                <div class="user-badge">
                    <i class="fas fa-user-circle"></i> <?php echo htmlspecialchars($username); ?> (<?php echo htmlspecialchars($userRole); ?>)
                </div>
                <button class="logout-btn" onclick="window.location.href='logout.php'">
                    <i class="fas fa-sign-out-alt"></i> Log Out
                </button>
            </div>
        </nav>
    </div>

    <!-- PAGE HEADER -->
    <div class="page-header">
        <h1 class="page-title">Backup & Restore System</h1>
        <p class="page-subtitle">Backup, restore, and manage data from all connected databases</p>
    </div>

    <!-- MAIN CONTENT -->
    <div class="main-content">
        <?php if ($message): ?>
            <div class="alert-message <?php echo $message_type === 'success' ? 'alert-success' : 'alert-error'; ?>">
                <?php echo $message; ?>
            </div>
        <?php endif; ?>
        
        <!-- DATABASE STATUS -->
        <div class="status-container">
            <div class="status-grid">
                <div class="status-card">
                    <div class="status-icon">
                        <i class="fas fa-database"></i>
                    </div>
                    <div class="status-name">MySQL</div>
                    <div class="status-indicator <?php echo $mysql_available ? 'status-online' : 'status-offline'; ?>">
                        <span class="status-dot <?php echo $mysql_available ? 'dot-online' : 'dot-offline'; ?>"></span>
                        <?php echo $mysql_available ? 'Connected' : 'Not Connected'; ?>
                    </div>
                    <div class="status-description">Your Local Database (Full Backup & Restore)</div>
                </div>
                
                <div class="status-card">
                    <div class="status-icon">
                        <i class="fas fa-server"></i>
                    </div>
                    <div class="status-name">SQL Server</div>
                    <div class="status-indicator <?php echo $sqlserver_available ? 'status-online' : 'status-offline'; ?>">
                        <span class="status-dot <?php echo $sqlserver_available ? 'dot-online' : 'dot-offline'; ?>"></span>
                        <?php echo $sqlserver_available ? 'Connected' : 'Not Connected'; ?>
                    </div>
                    <div class="status-description">Team Member Database (Backup Only)</div>
                </div>
                
                <div class="status-card">
                    <div class="status-icon">
                        <i class="fas fa-database"></i>
                    </div>
                    <div class="status-name">PostgreSQL</div>
                    <div class="status-indicator <?php echo $postgresql_available ? 'status-online' : 'status-offline'; ?>">
                        <span class="status-dot <?php echo $postgresql_available ? 'dot-online' : 'dot-offline'; ?>"></span>
                        <?php echo $postgresql_available ? 'Connected' : 'Not Connected'; ?>
                    </div>
                    <div class="status-description">Team Member Database (Backup Only)</div>
                </div>
            </div>
        </div>
        
        <!-- BACKUP STATISTICS -->
        <div class="status-container">
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value"><?php echo count($backup_files); ?></div>
                    <div class="stat-label">Total Backups</div>
                </div>
                
                <div class="stat-card">
                    <div class="stat-value">
                        <?php
                        echo formatBytes($total_size);
                        ?>
                    </div>
                    <div class="stat-label">Storage Used</div>
                </div>
                
                <div class="stat-card">
                    <div class="stat-value">
                        <?php echo count(array_filter($backup_files, function($f) { return strpos($f, '_mysql_') !== false; })); ?>
                    </div>
                    <div class="stat-label">MySQL Backups</div>
                </div>
                
                <div class="stat-card">
                    <div class="stat-value">
                        <?php echo count(array_filter($backup_files, function($f) { 
                            return strpos($f, '_sqlserver_') !== false || strpos($f, '_postgresql_') !== false; 
                        })); ?>
                    </div>
                    <div class="stat-label">Team Backups</div>
                </div>
            </div>
        </div>
        
        <!-- BACKUP CONTROL PANEL -->
        <div class="backup-container">
            <!-- TAB NAVIGATION -->
            <div class="tab-navigation">
                <button class="tab-button active" onclick="showTab('create')">
                    <i class="fas fa-plus-circle"></i> Create Backup
                </button>
                <button class="tab-button" onclick="showTab('restore')">
                    <i class="fas fa-history"></i> Restore
                </button>
                <button class="tab-button" onclick="showTab('upload')">
                    <i class="fas fa-upload"></i> Upload
                </button>
                <button class="tab-button" onclick="showTab('files')">
                    <i class="fas fa-folder-open"></i> Backup Files
                </button>
            </div>
            
            <!-- CREATE BACKUP TAB -->
            <div id="tab-create" class="tab-content active">
                <div class="backup-form">
                    <h3 style="color: #1a2980; margin-bottom: 25px; text-align: center;">
                        <i class="fas fa-cloud-upload-alt"></i> Create New Database Backup
                    </h3>
                    
                    <form method="POST" action="">
                        <div class="form-group">
                            <label class="form-label">Select Database</label>
                            <select name="database_type" class="form-control" onchange="updateDbStatus(this.value)">
                                <option value="mysql" <?php echo $mysql_available ? '' : 'disabled'; ?>>
                                    MySQL <?php echo $mysql_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                </option>
                                <option value="sqlserver" <?php echo $sqlserver_available ? '' : 'disabled'; ?>>
                                    SQL Server <?php echo $sqlserver_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                </option>
                                <option value="postgresql" <?php echo $postgresql_available ? '' : 'disabled'; ?>>
                                    PostgreSQL <?php echo $postgresql_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                </option>
                            </select>
                            <small id="db-status-text" style="color: #666; margin-top: 5px; display: block;">
                                <?php echo $mysql_available ? 'MySQL is available for backup' : 'Select an available database'; ?>
                            </small>
                        </div>
                        
                        <div class="form-group">
                            <label class="form-label">Backup Format</label>
                            <div class="format-grid">
                                <div class="format-card sql" onclick="selectFormat('sql')" id="format-sql">
                                    <div class="format-icon">
                                        <i class="fas fa-database"></i>
                                    </div>
                                    <div class="format-title">SQL Format</div>
                                    <ul class="format-features">
                                        <li>Creates .sql file</li>
                                        <li>Contains INSERT statements</li>
                                        <li>Best for database restoration</li>
                                        <li>Compatible with all databases</li>
                                    </ul>
                                </div>
                                
                                <div class="format-card excel" onclick="selectFormat('excel')" id="format-excel">
                                    <div class="format-icon">
                                        <i class="fas fa-file-excel"></i>
                                    </div>
                                    <div class="format-title">Excel/CSV Format</div>
                                    <ul class="format-features">
                                        <li>Creates .zip with CSV files</li>
                                        <li>Open in Excel/Google Sheets</li>
                                        <li>Best for reporting/analysis</li>
                                        <li>Easy data sharing</li>
                                    </ul>
                                </div>
                            </div>
                            <input type="hidden" name="backup_format" id="backup_format" value="sql">
                        </div>
                        
                        <div class="form-group">
                            <label class="form-label">Backup Name (Optional)</label>
                            <input type="text" name="backup_name" class="form-control" 
                                   value="Pharmacy_Backup_<?php echo date('Y-m-d'); ?>" 
                                   placeholder="Enter a descriptive name for your backup">
                        </div>
                        
                        <button type="submit" name="create_backup" class="btn-backup">
                            <i class="fas fa-rocket"></i> Create Backup Now
                        </button>
                        
                        <p style="margin-top: 15px; text-align: center; color: #666; font-size: 13px;">
                            <i class="fas fa-info-circle"></i> This will backup all tables: USER, PATIENT, MEDICINE, PRESCRIPTION, PRESCRIPTION_DETAIL
                        </p>
                    </form>
                </div>
            </div>
            
            <!-- RESTORE TAB -->
            <div id="tab-restore" class="tab-content">
                <div class="backup-form">
                    <h3 style="color: #1a2980; margin-bottom: 25px; text-align: center;">
                        <i class="fas fa-history"></i> Restore Database from Backup
                    </h3>
                    
                    <div class="restore-warning">
                        <h4><i class="fas fa-exclamation-triangle"></i> IMPORTANT WARNING</h4>
                        <p>Restoring a backup will OVERWRITE all existing data in the selected database. This action cannot be undone.</p>
                        <ul style="margin: 10px 0; padding-left: 20px;">
                            <li>Make sure you have a current backup before proceeding</li>
                            <li>Only restore to the same database type (MySQL to MySQL, etc.)</li>
                            <li>Large restores may take several minutes</li>
                            <li>All users will be logged out during restoration</li>
                        </ul>
                    </div>
                    
                    <form method="POST" action="" onsubmit="return confirmRestore()">
                        <div class="form-group">
                            <label class="form-label">Select Backup File</label>
                            <select name="backup_file" class="form-control" required>
                                <option value="">-- Select a backup file --</option>
                                <?php foreach ($backup_files as $file): 
                                    $filepath = $db_backup_dir . $file;
                                    if (file_exists($filepath)):
                                ?>
                                    <option value="<?php echo htmlspecialchars($file); ?>">
                                        <?php echo htmlspecialchars($file); ?> 
                                        (<?php echo date('M d, Y H:i', filemtime($filepath)); ?>)
                                    </option>
                                <?php endif; endforeach; ?>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label class="form-label">Target Database</label>
                            <select name="database_type" class="form-control" required>
                                <option value="mysql" <?php echo $mysql_available ? '' : 'disabled'; ?>>
                                    MySQL <?php echo $mysql_available ? '✅ Connected' : '❌ Not Connected'; ?>
                                </option>
                                <option value="sqlserver" disabled>SQL Server (Restore not available)</option>
                                <option value="postgresql" disabled>PostgreSQL (Restore not available)</option>
                            </select>
                            <small style="color: #666; margin-top: 5px; display: block;">
                                Note: Restoration is only available for MySQL. Team databases are read-only.
                            </small>
                        </div>
                        
                        <div class="form-group">
                            <label class="form-label">
                                <i class="fas fa-exclamation-circle"></i> Type "YES" to confirm
                            </label>
                            <input type="text" name="confirmation" class="form-control confirmation-input" 
                                   placeholder="TYPE: YES" required pattern="YES">
                            <small style="color: #666; margin-top: 5px; display: block;">
                                This is required to prevent accidental data loss
                            </small>
                        </div>
                        
                        <button type="submit" name="restore_backup" class="btn-danger">
                            <i class="fas fa-bomb"></i> RESTORE DATABASE NOW
                        </button>
                    </form>
                </div>
            </div>
            
            <!-- UPLOAD TAB -->
            <div id="tab-upload" class="tab-content">
                <div class="backup-form">
                    <h3 style="color: #1a2980; margin-bottom: 25px; text-align: center;">
                        <i class="fas fa-cloud-upload-alt"></i> Upload Backup File
                    </h3>
                    
                    <form method="POST" action="" enctype="multipart/form-data">
                        <div class="upload-area" onclick="document.getElementById('fileInput').click()">
                            <i class="fas fa-file-upload" style="font-size: 48px; color: #26d0ce; margin-bottom: 15px;"></i>
                            <h4>Click to select backup file</h4>
                            <p style="color: #666;">Supported formats: .sql, .zip</p>
                            <p style="color: #999; font-size: 12px;">Max file size: 50MB</p>
                            <input type="file" id="fileInput" name="backup_file" 
                                   accept=".sql,.zip" style="display: none;" 
                                   onchange="document.getElementById('fileName').textContent = this.files[0].name">
                            <div id="fileName" style="margin-top: 15px; font-weight: 600; color: #1a2980;"></div>
                        </div>
                        
                        <div class="form-group">
                            <label class="form-label">File Description (Optional)</label>
                            <input type="text" name="description" class="form-control" 
                                   placeholder="e.g., Emergency backup from Dec 2024">
                        </div>
                        
                        <button type="submit" name="upload_restore" class="btn-backup">
                            <i class="fas fa-upload"></i> Upload Backup File
                        </button>
                    </form>
                </div>
            </div>
            
            <!-- BACKUP FILES TAB -->
            <div id="tab-files" class="tab-content">
                <div style="background: white; border-radius: 10px; padding: 20px;">
                    <h3 style="color: #1a2980; margin-bottom: 20px; text-align: center;">
                        <i class="fas fa-archive"></i> Backup Files Archive
                    </h3>
                    
                    <?php if (count($backup_files) > 0): ?>
                        <table class="files-table">
                            <thead>
                                <tr>
                                    <th>Filename</th>
                                    <th>Database</th>
                                    <th>Format</th>
                                    <th>Size</th>
                                    <th>Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($backup_files as $file): 
                                    $filepath = $db_backup_dir . $file;
                                    $filesize = file_exists($filepath) ? formatBytes(filesize($filepath)) : 'N/A';
                                    $filedate = file_exists($filepath) ? date('M d, Y H:i', filemtime($filepath)) : 'N/A';
                                    $fileext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
                                    
                                    // Determine database type from filename
                                    if (strpos($file, '_mysql_') !== false) {
                                        $db_type = 'MySQL';
                                        $db_class = 'badge-mysql';
                                    } elseif (strpos($file, '_sqlserver_') !== false) {
                                        $db_type = 'SQL Server';
                                        $db_class = 'badge-sqlserver';
                                    } elseif (strpos($file, '_postgresql_') !== false) {
                                        $db_type = 'PostgreSQL';
                                        $db_class = 'badge-postgresql';
                                    } else {
                                        $db_type = 'Unknown';
                                        $db_class = 'badge-format';
                                    }
                                    
                                    $format = ($fileext === 'zip') ? 'Excel/CSV' : 'SQL';
                                ?>
                                    <tr>
                                        <td style="font-weight: 600;"><?php echo htmlspecialchars($file); ?></td>
                                        <td><span class="file-badge <?php echo $db_class; ?>"><?php echo $db_type; ?></span></td>
                                        <td><span class="file-badge badge-format"><?php echo $format; ?></span></td>
                                        <td><?php echo $filesize; ?></td>
                                        <td><?php echo $filedate; ?></td>
                                        <td>
                                            <div class="action-buttons">
                                                <a href="backups/database/<?php echo urlencode($file); ?>" 
                                                   download class="btn-action btn-download">
                                                    <i class="fas fa-download"></i> Download
                                                </a>
                                                <a href="?delete=<?php echo urlencode($file); ?>" 
                                                   class="btn-action btn-delete"
                                                   onclick="return confirm('Are you sure you want to delete <?php echo htmlspecialchars($file); ?>?')">
                                                    <i class="fas fa-trash"></i> Delete
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <div style="text-align: center; padding: 40px; background: #f8f9fa; border-radius: 8px;">
                            <i class="fas fa-folder-open" style="font-size: 48px; color: #ccc; margin-bottom: 15px;"></i>
                            <p style="color: #666; font-size: 1.1em;">No backup files found</p>
                            <p style="color: #999; margin-top: 10px;">Create your first backup using the "Create Backup" tab</p>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Scroll effect for oval navigation
        const ovalNav = document.getElementById('ovalNav');
        const ovalNavInner = document.getElementById('ovalNavInner');
        
        window.addEventListener('scroll', () => {
            if (window.innerWidth > 992) {
                if (window.scrollY > 50) {
                    ovalNav.classList.add('scrolled');
                    ovalNavInner.classList.add('scrolled');
                } else {
                    ovalNav.classList.remove('scrolled');
                    ovalNavInner.classList.remove('scrolled');
                }
            }
        });
        
        // Tab functionality
        function showTab(tabName) {
            // Hide all tabs
            document.querySelectorAll('.tab-content').forEach(tab => {
                tab.classList.remove('active');
            });
            
            // Remove active class from all tab buttons
            document.querySelectorAll('.tab-button').forEach(button => {
                button.classList.remove('active');
            });
            
            // Show selected tab
            document.getElementById('tab-' + tabName).classList.add('active');
            
            // Add active class to clicked tab button
            event.target.classList.add('active');
        }
        
        // Format selection
        function selectFormat(format) {
            // Remove selected class from all format cards
            document.querySelectorAll('.format-card').forEach(card => {
                card.classList.remove('selected');
            });
            
            // Add selected class to clicked card
            document.getElementById('format-' + format).classList.add('selected');
            
            // Set hidden input value
            document.getElementById('backup_format').value = format;
        }
        
        // Database status update
        function updateDbStatus(selectedDb) {
            const statusText = document.getElementById('db-status-text');
            const dbStatus = {
                'mysql': '<?php echo $mysql_available ? "✅ MySQL is available for backup" : "❌ MySQL is not connected"; ?>',
                'sqlserver': '<?php echo $sqlserver_available ? "✅ SQL Server is available for backup" : "❌ SQL Server is not connected"; ?>',
                'postgresql': '<?php echo $postgresql_available ? "✅ PostgreSQL is available for backup" : "❌ PostgreSQL is not connected"; ?>'
            };
            statusText.textContent = dbStatus[selectedDb] || 'Select a database';
        }
        
        // Restore confirmation
        function confirmRestore() {
            const confirmation = document.querySelector('input[name="confirmation"]').value;
            if (confirmation !== 'YES') {
                alert('You must type YES to confirm restoration');
                return false;
            }
            
            return confirm('⚠️ FINAL WARNING: This will OVERWRITE all data in your database.\n\nThis action cannot be undone!\n\nAre you absolutely sure?');
        }
        
        // Initialize format selection
        document.addEventListener('DOMContentLoaded', function() {
            selectFormat('sql');
            
            const select = document.querySelector('select[name="database_type"]');
            if (select) {
                updateDbStatus(select.value);
            }
        });
    </script>
</body>
</html>
<?php
// Helper function to format file sizes
function formatBytes($bytes, $precision = 2) {
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    
    return round($bytes, $precision) . ' ' . $units[$pow];
}